x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "7"

services:
  master:
    build:
      context: .
      dockerfile: dockerfile
      args:
        CMD_PATH: master
    container_name: sm_master
    restart: unless-stopped
    ports:
      - "8080:8080"  
    volumes:
      - ./config/master/.env.master:/app/config/master/.env.master
    networks:
      sm_network:
        ipv4_address: 10.10.10.20
    logging: *default-logging
  
  worker:
    build:
      context: .
      dockerfile: dockerfile
      args:
        CMD_PATH: worker
    restart: unless-stopped
    deploy:
      replicas: 3
    volumes:
      - ./config/worker/.env.worker:/app/config/worker/.env.worker
    networks:
      - sm_network
    logging: *default-logging

  eswriter:
    build:
      context: .
      dockerfile: dockerfile
      args:
        CMD_PATH: eswriter
    restart: unless-stopped
    volumes:
      - ./config/eswriter/.env.eswriter:/app/config/eswriter/.env.eswriter
    networks:
      - sm_network
    logging: *default-logging

  pgwriter:
    build:
      context: .
      dockerfile: dockerfile
      args:
        CMD_PATH: pgwriter
    restart: unless-stopped
    volumes:
      - ./config/pgwriter/.env.pgwriter:/app/config/pgwriter/.env.pgwriter
    networks:
      - sm_network
    logging: *default-logging

  gw:
    build:
      context: .
      dockerfile: dockerfile
      args:
        CMD_PATH: gw
    container_name: sm_gw
    restart: unless-stopped
    ports:
      - "8082:8080"  
    volumes:
      - ./config/gw/.env.gw:/app/config/gw/.env.gw
    networks:
      sm_network:
        ipv4_address: 10.10.10.21
    logging: *default-logging

networks:
  sm_network:
    external: true
    name: server-management_default