services:
  postgres:
    image: postgres:16
    container_name: sm_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: server_management
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin", "-d", "server_management"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: sm_redis
    restart: unless-stopped
    command: >
      redis-server
      --requirepass 123456
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  kafka:
    image: apache/kafka:3.7.1
    container_name: sm_kafka
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      # KRaft
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@sm_kafka:9093
      # Listeners
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,INTERNAL://sm_kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      # Single node
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      # KRaft cluster id
      KAFKA_CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

      KAFKA_LOG_RETENTION_MS: 3600000        # Giữ message 1 giờ
      KAFKA_LOG_RETENTION_BYTES: -1          # Không giới hạn theo dung lượng (-1 = tắt)
      KAFKA_LOG_SEGMENT_BYTES: 104857600     # Segment 100MB (nhỏ hơn → xóa nhanh hơn)
      KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS: 60000  # Kiểm tra mỗi 1 phút
    healthcheck:
      test: ["CMD", "/opt/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:29092", "--list"]
      interval: 10s
      timeout: 10s
      retries: 10

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: sm_elasticsearch
    restart: unless-stopped
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"

      # JVM
      ES_JAVA_OPTS: -Xms512m -Xmx512m

    ports:
      - "9200:9200"

    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9200/_cluster/health"]
      interval: 10s
      timeout: 10s
      retries: 10

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: sm_swagger
    ports:
      - "8081:8080"
    environment:
      SWAGGER_JSON: /api/openapi.yaml
    volumes:
      - ./api/openapi.yaml:/api/openapi.yaml

  migrate:
    image: migrate/migrate:v4.17.0
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./migrations:/migrations
    entrypoint: >
      migrate -path=/migrations
      -database postgres://admin:123456@postgres:5432/server_management?sslmode=disable
      up

  kafka-init:
    image: apache/kafka:3.7.1
    container_name: kafka_init
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./scripts/kafka.sh:/kafka.sh
    entrypoint: ["bash", "/kafka.sh"]

  es-init:
    image: curlimages/curl:8.5.0
    container_name: es_init
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./scripts/es.sh:/es.sh
    entrypoint: ["sh", "/es.sh"]
  
volumes:
  postgres_data:
  redis_data:
  elasticsearch_data:

networks:
  default:
    name: server-management_default