// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockServerRepositoryInterface is an autogenerated mock type for the ServerRepositoryInterface type
type MockServerRepositoryInterface struct {
	mock.Mock
}

type MockServerRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerRepositoryInterface) EXPECT() *MockServerRepositoryInterface_Expecter {
	return &MockServerRepositoryInterface_Expecter{mock: &_m.Mock}
}

// AllMetadata provides a mock function with given fields: ctx
func (_m *MockServerRepositoryInterface) AllMetadata(ctx context.Context) ([]model.ServerMetadata, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for AllMetadata")
	}

	var r0 []model.ServerMetadata
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]model.ServerMetadata, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []model.ServerMetadata); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ServerMetadata)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepositoryInterface_AllMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllMetadata'
type MockServerRepositoryInterface_AllMetadata_Call struct {
	*mock.Call
}

// AllMetadata is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerRepositoryInterface_Expecter) AllMetadata(ctx interface{}) *MockServerRepositoryInterface_AllMetadata_Call {
	return &MockServerRepositoryInterface_AllMetadata_Call{Call: _e.mock.On("AllMetadata", ctx)}
}

func (_c *MockServerRepositoryInterface_AllMetadata_Call) Run(run func(ctx context.Context)) *MockServerRepositoryInterface_AllMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_AllMetadata_Call) Return(_a0 []model.ServerMetadata, _a1 error) *MockServerRepositoryInterface_AllMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepositoryInterface_AllMetadata_Call) RunAndReturn(run func(context.Context) ([]model.ServerMetadata, error)) *MockServerRepositoryInterface_AllMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// BulkUpdateServers provides a mock function with given fields: ctx, items
func (_m *MockServerRepositoryInterface) BulkUpdateServers(ctx context.Context, items []model.Server) error {
	ret := _m.Called(ctx, items)

	if len(ret) == 0 {
		panic("no return value specified for BulkUpdateServers")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Server) error); ok {
		r0 = rf(ctx, items)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepositoryInterface_BulkUpdateServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BulkUpdateServers'
type MockServerRepositoryInterface_BulkUpdateServers_Call struct {
	*mock.Call
}

// BulkUpdateServers is a helper method to define mock.On call
//   - ctx context.Context
//   - items []model.Server
func (_e *MockServerRepositoryInterface_Expecter) BulkUpdateServers(ctx interface{}, items interface{}) *MockServerRepositoryInterface_BulkUpdateServers_Call {
	return &MockServerRepositoryInterface_BulkUpdateServers_Call{Call: _e.mock.On("BulkUpdateServers", ctx, items)}
}

func (_c *MockServerRepositoryInterface_BulkUpdateServers_Call) Run(run func(ctx context.Context, items []model.Server)) *MockServerRepositoryInterface_BulkUpdateServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.Server))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_BulkUpdateServers_Call) Return(_a0 error) *MockServerRepositoryInterface_BulkUpdateServers_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepositoryInterface_BulkUpdateServers_Call) RunAndReturn(run func(context.Context, []model.Server) error) *MockServerRepositoryInterface_BulkUpdateServers_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockServerRepositoryInterface) Create(ctx context.Context, s *model.Server) error {
	ret := _m.Called(ctx, s)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Server) error); ok {
		r0 = rf(ctx, s)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepositoryInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServerRepositoryInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s *model.Server
func (_e *MockServerRepositoryInterface_Expecter) Create(ctx interface{}, s interface{}) *MockServerRepositoryInterface_Create_Call {
	return &MockServerRepositoryInterface_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockServerRepositoryInterface_Create_Call) Run(run func(ctx context.Context, s *model.Server)) *MockServerRepositoryInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Server))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_Create_Call) Return(_a0 error) *MockServerRepositoryInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepositoryInterface_Create_Call) RunAndReturn(run func(context.Context, *model.Server) error) *MockServerRepositoryInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateBatch provides a mock function with given fields: ctx, servers
func (_m *MockServerRepositoryInterface) CreateBatch(ctx context.Context, servers []model.Server) (*model.CreateBatchServerResult, error) {
	ret := _m.Called(ctx, servers)

	if len(ret) == 0 {
		panic("no return value specified for CreateBatch")
	}

	var r0 *model.CreateBatchServerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.Server) (*model.CreateBatchServerResult, error)); ok {
		return rf(ctx, servers)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.Server) *model.CreateBatchServerResult); ok {
		r0 = rf(ctx, servers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateBatchServerResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.Server) error); ok {
		r1 = rf(ctx, servers)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepositoryInterface_CreateBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBatch'
type MockServerRepositoryInterface_CreateBatch_Call struct {
	*mock.Call
}

// CreateBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - servers []model.Server
func (_e *MockServerRepositoryInterface_Expecter) CreateBatch(ctx interface{}, servers interface{}) *MockServerRepositoryInterface_CreateBatch_Call {
	return &MockServerRepositoryInterface_CreateBatch_Call{Call: _e.mock.On("CreateBatch", ctx, servers)}
}

func (_c *MockServerRepositoryInterface_CreateBatch_Call) Run(run func(ctx context.Context, servers []model.Server)) *MockServerRepositoryInterface_CreateBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.Server))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_CreateBatch_Call) Return(_a0 *model.CreateBatchServerResult, _a1 error) *MockServerRepositoryInterface_CreateBatch_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepositoryInterface_CreateBatch_Call) RunAndReturn(run func(context.Context, []model.Server) (*model.CreateBatchServerResult, error)) *MockServerRepositoryInterface_CreateBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockServerRepositoryInterface) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerRepositoryInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServerRepositoryInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockServerRepositoryInterface_Expecter) Delete(ctx interface{}, id interface{}) *MockServerRepositoryInterface_Delete_Call {
	return &MockServerRepositoryInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockServerRepositoryInterface_Delete_Call) Run(run func(ctx context.Context, id string)) *MockServerRepositoryInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_Delete_Call) Return(_a0 error) *MockServerRepositoryInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerRepositoryInterface_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockServerRepositoryInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, filter
func (_m *MockServerRepositoryInterface) List(ctx context.Context, filter model.ListServerFilter) (*model.ListServerResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *model.ListServerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ListServerFilter) (*model.ListServerResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListServerFilter) *model.ListServerResult); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListServerResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListServerFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepositoryInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServerRepositoryInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.ListServerFilter
func (_e *MockServerRepositoryInterface_Expecter) List(ctx interface{}, filter interface{}) *MockServerRepositoryInterface_List_Call {
	return &MockServerRepositoryInterface_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockServerRepositoryInterface_List_Call) Run(run func(ctx context.Context, filter model.ListServerFilter)) *MockServerRepositoryInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ListServerFilter))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_List_Call) Return(_a0 *model.ListServerResult, _a1 error) *MockServerRepositoryInterface_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepositoryInterface_List_Call) RunAndReturn(run func(context.Context, model.ListServerFilter) (*model.ListServerResult, error)) *MockServerRepositoryInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, id, fields
func (_m *MockServerRepositoryInterface) Update(ctx context.Context, id string, fields map[string]interface{}) (*model.Server, error) {
	ret := _m.Called(ctx, id, fields)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) (*model.Server, error)); ok {
		return rf(ctx, id, fields)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}) *model.Server); ok {
		r0 = rf(ctx, id, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, id, fields)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerRepositoryInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServerRepositoryInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - fields map[string]interface{}
func (_e *MockServerRepositoryInterface_Expecter) Update(ctx interface{}, id interface{}, fields interface{}) *MockServerRepositoryInterface_Update_Call {
	return &MockServerRepositoryInterface_Update_Call{Call: _e.mock.On("Update", ctx, id, fields)}
}

func (_c *MockServerRepositoryInterface_Update_Call) Run(run func(ctx context.Context, id string, fields map[string]interface{})) *MockServerRepositoryInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}))
	})
	return _c
}

func (_c *MockServerRepositoryInterface_Update_Call) Return(_a0 *model.Server, _a1 error) *MockServerRepositoryInterface_Update_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerRepositoryInterface_Update_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}) (*model.Server, error)) *MockServerRepositoryInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerRepositoryInterface creates a new instance of MockServerRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerRepositoryInterface {
	mock := &MockServerRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
