// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockGWServiceInterface is an autogenerated mock type for the GWServiceInterface type
type MockGWServiceInterface struct {
	mock.Mock
}

type MockGWServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGWServiceInterface) EXPECT() *MockGWServiceInterface_Expecter {
	return &MockGWServiceInterface_Expecter{mock: &_m.Mock}
}

// PublishHeartbeat provides a mock function with given fields: ctx, heartbeat
func (_m *MockGWServiceInterface) PublishHeartbeat(ctx context.Context, heartbeat model.Heartbeat) error {
	ret := _m.Called(ctx, heartbeat)

	if len(ret) == 0 {
		panic("no return value specified for PublishHeartbeat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Heartbeat) error); ok {
		r0 = rf(ctx, heartbeat)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGWServiceInterface_PublishHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishHeartbeat'
type MockGWServiceInterface_PublishHeartbeat_Call struct {
	*mock.Call
}

// PublishHeartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - heartbeat model.Heartbeat
func (_e *MockGWServiceInterface_Expecter) PublishHeartbeat(ctx interface{}, heartbeat interface{}) *MockGWServiceInterface_PublishHeartbeat_Call {
	return &MockGWServiceInterface_PublishHeartbeat_Call{Call: _e.mock.On("PublishHeartbeat", ctx, heartbeat)}
}

func (_c *MockGWServiceInterface_PublishHeartbeat_Call) Run(run func(ctx context.Context, heartbeat model.Heartbeat)) *MockGWServiceInterface_PublishHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Heartbeat))
	})
	return _c
}

func (_c *MockGWServiceInterface_PublishHeartbeat_Call) Return(_a0 error) *MockGWServiceInterface_PublishHeartbeat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGWServiceInterface_PublishHeartbeat_Call) RunAndReturn(run func(context.Context, model.Heartbeat) error) *MockGWServiceInterface_PublishHeartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGWServiceInterface creates a new instance of MockGWServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGWServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGWServiceInterface {
	mock := &MockGWServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
