// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"

	model "github.com/LeHuuHai/server-management/internal/model"
)

// MockServerDeserializer is an autogenerated mock type for the ServerDeserializer type
type MockServerDeserializer struct {
	mock.Mock
}

type MockServerDeserializer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerDeserializer) EXPECT() *MockServerDeserializer_Expecter {
	return &MockServerDeserializer_Expecter{mock: &_m.Mock}
}

// Deserialize provides a mock function with given fields: ctx, reader
func (_m *MockServerDeserializer) Deserialize(ctx context.Context, reader io.Reader) ([]model.ServerImport, error) {
	ret := _m.Called(ctx, reader)

	if len(ret) == 0 {
		panic("no return value specified for Deserialize")
	}

	var r0 []model.ServerImport
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) ([]model.ServerImport, error)); ok {
		return rf(ctx, reader)
	}
	if rf, ok := ret.Get(0).(func(context.Context, io.Reader) []model.ServerImport); ok {
		r0 = rf(ctx, reader)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ServerImport)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, io.Reader) error); ok {
		r1 = rf(ctx, reader)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerDeserializer_Deserialize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deserialize'
type MockServerDeserializer_Deserialize_Call struct {
	*mock.Call
}

// Deserialize is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.Reader
func (_e *MockServerDeserializer_Expecter) Deserialize(ctx interface{}, reader interface{}) *MockServerDeserializer_Deserialize_Call {
	return &MockServerDeserializer_Deserialize_Call{Call: _e.mock.On("Deserialize", ctx, reader)}
}

func (_c *MockServerDeserializer_Deserialize_Call) Run(run func(ctx context.Context, reader io.Reader)) *MockServerDeserializer_Deserialize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Reader))
	})
	return _c
}

func (_c *MockServerDeserializer_Deserialize_Call) Return(_a0 []model.ServerImport, _a1 error) *MockServerDeserializer_Deserialize_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerDeserializer_Deserialize_Call) RunAndReturn(run func(context.Context, io.Reader) ([]model.ServerImport, error)) *MockServerDeserializer_Deserialize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerDeserializer creates a new instance of MockServerDeserializer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerDeserializer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerDeserializer {
	mock := &MockServerDeserializer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
