// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	model "github.com/LeHuuHai/server-management/internal/model"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *MockSender) Close() {
	_m.Called()
}

// MockSender_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockSender_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockSender_Expecter) Close() *MockSender_Close_Call {
	return &MockSender_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockSender_Close_Call) Run(run func()) *MockSender_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSender_Close_Call) Return() *MockSender_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSender_Close_Call) RunAndReturn(run func()) *MockSender_Close_Call {
	_c.Run(run)
	return _c
}

// Send provides a mock function with given fields: ctx, m
func (_m *MockSender) Send(ctx context.Context, m model.Mail) error {
	ret := _m.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.Mail) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSender_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - m model.Mail
func (_e *MockSender_Expecter) Send(ctx interface{}, m interface{}) *MockSender_Send_Call {
	return &MockSender_Send_Call{Call: _e.mock.On("Send", ctx, m)}
}

func (_c *MockSender_Send_Call) Run(run func(ctx context.Context, m model.Mail)) *MockSender_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Mail))
	})
	return _c
}

func (_c *MockSender_Send_Call) Return(_a0 error) *MockSender_Send_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_Send_Call) RunAndReturn(run func(context.Context, model.Mail) error) *MockSender_Send_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
