// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAuthServiceInterface is an autogenerated mock type for the AuthServiceInterface type
type MockAuthServiceInterface struct {
	mock.Mock
}

type MockAuthServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAuthServiceInterface) EXPECT() *MockAuthServiceInterface_Expecter {
	return &MockAuthServiceInterface_Expecter{mock: &_m.Mock}
}

// HashPassword provides a mock function with given fields: password
func (_m *MockAuthServiceInterface) HashPassword(password string) (string, error) {
	ret := _m.Called(password)

	if len(ret) == 0 {
		panic("no return value specified for HashPassword")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(password)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_HashPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashPassword'
type MockAuthServiceInterface_HashPassword_Call struct {
	*mock.Call
}

// HashPassword is a helper method to define mock.On call
//   - password string
func (_e *MockAuthServiceInterface_Expecter) HashPassword(password interface{}) *MockAuthServiceInterface_HashPassword_Call {
	return &MockAuthServiceInterface_HashPassword_Call{Call: _e.mock.On("HashPassword", password)}
}

func (_c *MockAuthServiceInterface_HashPassword_Call) Run(run func(password string)) *MockAuthServiceInterface_HashPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_HashPassword_Call) Return(_a0 string, _a1 error) *MockAuthServiceInterface_HashPassword_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_HashPassword_Call) RunAndReturn(run func(string) (string, error)) *MockAuthServiceInterface_HashPassword_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: userName, password
func (_m *MockAuthServiceInterface) Login(userName string, password string) (*model.LoginResult, error) {
	ret := _m.Called(userName, password)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 *model.LoginResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.LoginResult, error)); ok {
		return rf(userName, password)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.LoginResult); ok {
		r0 = rf(userName, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.LoginResult)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(userName, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type MockAuthServiceInterface_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - userName string
//   - password string
func (_e *MockAuthServiceInterface_Expecter) Login(userName interface{}, password interface{}) *MockAuthServiceInterface_Login_Call {
	return &MockAuthServiceInterface_Login_Call{Call: _e.mock.On("Login", userName, password)}
}

func (_c *MockAuthServiceInterface_Login_Call) Run(run func(userName string, password string)) *MockAuthServiceInterface_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Login_Call) Return(_a0 *model.LoginResult, _a1 error) *MockAuthServiceInterface_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_Login_Call) RunAndReturn(run func(string, string) (*model.LoginResult, error)) *MockAuthServiceInterface_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Logout provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthServiceInterface) Logout(ctx context.Context, refreshToken string) error {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for Logout")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAuthServiceInterface_Logout_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logout'
type MockAuthServiceInterface_Logout_Call struct {
	*mock.Call
}

// Logout is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthServiceInterface_Expecter) Logout(ctx interface{}, refreshToken interface{}) *MockAuthServiceInterface_Logout_Call {
	return &MockAuthServiceInterface_Logout_Call{Call: _e.mock.On("Logout", ctx, refreshToken)}
}

func (_c *MockAuthServiceInterface_Logout_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_Logout_Call) Return(_a0 error) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAuthServiceInterface_Logout_Call) RunAndReturn(run func(context.Context, string) error) *MockAuthServiceInterface_Logout_Call {
	_c.Call.Return(run)
	return _c
}

// RefreshAccessToken provides a mock function with given fields: ctx, refreshToken
func (_m *MockAuthServiceInterface) RefreshAccessToken(ctx context.Context, refreshToken string) (string, error) {
	ret := _m.Called(ctx, refreshToken)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, refreshToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, refreshToken)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, refreshToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAuthServiceInterface_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockAuthServiceInterface_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - refreshToken string
func (_e *MockAuthServiceInterface_Expecter) RefreshAccessToken(ctx interface{}, refreshToken interface{}) *MockAuthServiceInterface_RefreshAccessToken_Call {
	return &MockAuthServiceInterface_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, refreshToken)}
}

func (_c *MockAuthServiceInterface_RefreshAccessToken_Call) Run(run func(ctx context.Context, refreshToken string)) *MockAuthServiceInterface_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAuthServiceInterface_RefreshAccessToken_Call) Return(_a0 string, _a1 error) *MockAuthServiceInterface_RefreshAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAuthServiceInterface_RefreshAccessToken_Call) RunAndReturn(run func(context.Context, string) (string, error)) *MockAuthServiceInterface_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAuthServiceInterface creates a new instance of MockAuthServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAuthServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAuthServiceInterface {
	mock := &MockAuthServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
