// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDownloadServiceInterface is an autogenerated mock type for the DownloadServiceInterface type
type MockDownloadServiceInterface struct {
	mock.Mock
}

type MockDownloadServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDownloadServiceInterface) EXPECT() *MockDownloadServiceInterface_Expecter {
	return &MockDownloadServiceInterface_Expecter{mock: &_m.Mock}
}

// Download provides a mock function with given fields: ctx, filename
func (_m *MockDownloadServiceInterface) Download(ctx context.Context, filename string) ([]byte, error) {
	ret := _m.Called(ctx, filename)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]byte, error)); ok {
		return rf(ctx, filename)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []byte); ok {
		r0 = rf(ctx, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, filename)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDownloadServiceInterface_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type MockDownloadServiceInterface_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - filename string
func (_e *MockDownloadServiceInterface_Expecter) Download(ctx interface{}, filename interface{}) *MockDownloadServiceInterface_Download_Call {
	return &MockDownloadServiceInterface_Download_Call{Call: _e.mock.On("Download", ctx, filename)}
}

func (_c *MockDownloadServiceInterface_Download_Call) Run(run func(ctx context.Context, filename string)) *MockDownloadServiceInterface_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDownloadServiceInterface_Download_Call) Return(_a0 []byte, _a1 error) *MockDownloadServiceInterface_Download_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDownloadServiceInterface_Download_Call) RunAndReturn(run func(context.Context, string) ([]byte, error)) *MockDownloadServiceInterface_Download_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDownloadServiceInterface creates a new instance of MockDownloadServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDownloadServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDownloadServiceInterface {
	mock := &MockDownloadServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
