// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockAccountRepoInterface is an autogenerated mock type for the AccountRepoInterface type
type MockAccountRepoInterface struct {
	mock.Mock
}

type MockAccountRepoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccountRepoInterface) EXPECT() *MockAccountRepoInterface_Expecter {
	return &MockAccountRepoInterface_Expecter{mock: &_m.Mock}
}

// FindByUserID provides a mock function with given fields: userID
func (_m *MockAccountRepoInterface) FindByUserID(userID uint) (*model.Account, error) {
	ret := _m.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserID")
	}

	var r0 *model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (*model.Account, error)); ok {
		return rf(userID)
	}
	if rf, ok := ret.Get(0).(func(uint) *model.Account); ok {
		r0 = rf(userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepoInterface_FindByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserID'
type MockAccountRepoInterface_FindByUserID_Call struct {
	*mock.Call
}

// FindByUserID is a helper method to define mock.On call
//   - userID uint
func (_e *MockAccountRepoInterface_Expecter) FindByUserID(userID interface{}) *MockAccountRepoInterface_FindByUserID_Call {
	return &MockAccountRepoInterface_FindByUserID_Call{Call: _e.mock.On("FindByUserID", userID)}
}

func (_c *MockAccountRepoInterface_FindByUserID_Call) Run(run func(userID uint)) *MockAccountRepoInterface_FindByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uint))
	})
	return _c
}

func (_c *MockAccountRepoInterface_FindByUserID_Call) Return(_a0 *model.Account, _a1 error) *MockAccountRepoInterface_FindByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepoInterface_FindByUserID_Call) RunAndReturn(run func(uint) (*model.Account, error)) *MockAccountRepoInterface_FindByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByUserName provides a mock function with given fields: userName
func (_m *MockAccountRepoInterface) FindByUserName(userName string) (*model.Account, error) {
	ret := _m.Called(userName)

	if len(ret) == 0 {
		panic("no return value specified for FindByUserName")
	}

	var r0 *model.Account
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*model.Account, error)); ok {
		return rf(userName)
	}
	if rf, ok := ret.Get(0).(func(string) *model.Account); ok {
		r0 = rf(userName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Account)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccountRepoInterface_FindByUserName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByUserName'
type MockAccountRepoInterface_FindByUserName_Call struct {
	*mock.Call
}

// FindByUserName is a helper method to define mock.On call
//   - userName string
func (_e *MockAccountRepoInterface_Expecter) FindByUserName(userName interface{}) *MockAccountRepoInterface_FindByUserName_Call {
	return &MockAccountRepoInterface_FindByUserName_Call{Call: _e.mock.On("FindByUserName", userName)}
}

func (_c *MockAccountRepoInterface_FindByUserName_Call) Run(run func(userName string)) *MockAccountRepoInterface_FindByUserName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAccountRepoInterface_FindByUserName_Call) Return(_a0 *model.Account, _a1 error) *MockAccountRepoInterface_FindByUserName_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccountRepoInterface_FindByUserName_Call) RunAndReturn(run func(string) (*model.Account, error)) *MockAccountRepoInterface_FindByUserName_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccountRepoInterface creates a new instance of MockAccountRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccountRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccountRepoInterface {
	mock := &MockAccountRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
