// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockReportServiceInterface is an autogenerated mock type for the ReportServiceInterface type
type MockReportServiceInterface struct {
	mock.Mock
}

type MockReportServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportServiceInterface) EXPECT() *MockReportServiceInterface_Expecter {
	return &MockReportServiceInterface_Expecter{mock: &_m.Mock}
}

// ReportServer provides a mock function with given fields: ctx, request
func (_m *MockReportServiceInterface) ReportServer(ctx context.Context, request model.GenServerReportRequest) error {
	ret := _m.Called(ctx, request)

	if len(ret) == 0 {
		panic("no return value specified for ReportServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.GenServerReportRequest) error); ok {
		r0 = rf(ctx, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportServiceInterface_ReportServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReportServer'
type MockReportServiceInterface_ReportServer_Call struct {
	*mock.Call
}

// ReportServer is a helper method to define mock.On call
//   - ctx context.Context
//   - request model.GenServerReportRequest
func (_e *MockReportServiceInterface_Expecter) ReportServer(ctx interface{}, request interface{}) *MockReportServiceInterface_ReportServer_Call {
	return &MockReportServiceInterface_ReportServer_Call{Call: _e.mock.On("ReportServer", ctx, request)}
}

func (_c *MockReportServiceInterface_ReportServer_Call) Run(run func(ctx context.Context, request model.GenServerReportRequest)) *MockReportServiceInterface_ReportServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.GenServerReportRequest))
	})
	return _c
}

func (_c *MockReportServiceInterface_ReportServer_Call) Return(_a0 error) *MockReportServiceInterface_ReportServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportServiceInterface_ReportServer_Call) RunAndReturn(run func(context.Context, model.GenServerReportRequest) error) *MockReportServiceInterface_ReportServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportServiceInterface creates a new instance of MockReportServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportServiceInterface {
	mock := &MockReportServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
