// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenBlocklist is an autogenerated mock type for the TokenBlocklist type
type MockTokenBlocklist struct {
	mock.Mock
}

type MockTokenBlocklist_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenBlocklist) EXPECT() *MockTokenBlocklist_Expecter {
	return &MockTokenBlocklist_Expecter{mock: &_m.Mock}
}

// IsRevoked provides a mock function with given fields: ctx, token
func (_m *MockTokenBlocklist) IsRevoked(ctx context.Context, token string) (bool, error) {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for IsRevoked")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return rf(ctx, token)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, token)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenBlocklist_IsRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsRevoked'
type MockTokenBlocklist_IsRevoked_Call struct {
	*mock.Call
}

// IsRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockTokenBlocklist_Expecter) IsRevoked(ctx interface{}, token interface{}) *MockTokenBlocklist_IsRevoked_Call {
	return &MockTokenBlocklist_IsRevoked_Call{Call: _e.mock.On("IsRevoked", ctx, token)}
}

func (_c *MockTokenBlocklist_IsRevoked_Call) Run(run func(ctx context.Context, token string)) *MockTokenBlocklist_IsRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenBlocklist_IsRevoked_Call) Return(_a0 bool, _a1 error) *MockTokenBlocklist_IsRevoked_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenBlocklist_IsRevoked_Call) RunAndReturn(run func(context.Context, string) (bool, error)) *MockTokenBlocklist_IsRevoked_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, token, expiry
func (_m *MockTokenBlocklist) Revoke(ctx context.Context, token string, expiry time.Time) error {
	ret := _m.Called(ctx, token, expiry)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, time.Time) error); ok {
		r0 = rf(ctx, token, expiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenBlocklist_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenBlocklist_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
//   - expiry time.Time
func (_e *MockTokenBlocklist_Expecter) Revoke(ctx interface{}, token interface{}, expiry interface{}) *MockTokenBlocklist_Revoke_Call {
	return &MockTokenBlocklist_Revoke_Call{Call: _e.mock.On("Revoke", ctx, token, expiry)}
}

func (_c *MockTokenBlocklist_Revoke_Call) Run(run func(ctx context.Context, token string, expiry time.Time)) *MockTokenBlocklist_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(time.Time))
	})
	return _c
}

func (_c *MockTokenBlocklist_Revoke_Call) Return(_a0 error) *MockTokenBlocklist_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenBlocklist_Revoke_Call) RunAndReturn(run func(context.Context, string, time.Time) error) *MockTokenBlocklist_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenBlocklist creates a new instance of MockTokenBlocklist. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenBlocklist(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenBlocklist {
	mock := &MockTokenBlocklist{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
