// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mq "github.com/LeHuuHai/server-management/internal/domain/mq"
	mock "github.com/stretchr/testify/mock"
)

// MockConsumer is an autogenerated mock type for the Consumer type
type MockConsumer struct {
	mock.Mock
}

type MockConsumer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConsumer) EXPECT() *MockConsumer_Expecter {
	return &MockConsumer_Expecter{mock: &_m.Mock}
}

// Commit provides a mock function with given fields: ctx, msg
func (_m *MockConsumer) Commit(ctx context.Context, msg *mq.Message) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *mq.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConsumer_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockConsumer_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
//   - msg *mq.Message
func (_e *MockConsumer_Expecter) Commit(ctx interface{}, msg interface{}) *MockConsumer_Commit_Call {
	return &MockConsumer_Commit_Call{Call: _e.mock.On("Commit", ctx, msg)}
}

func (_c *MockConsumer_Commit_Call) Run(run func(ctx context.Context, msg *mq.Message)) *MockConsumer_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*mq.Message))
	})
	return _c
}

func (_c *MockConsumer_Commit_Call) Return(_a0 error) *MockConsumer_Commit_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConsumer_Commit_Call) RunAndReturn(run func(context.Context, *mq.Message) error) *MockConsumer_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: _a0
func (_m *MockConsumer) Read(_a0 context.Context) (*mq.Message, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 *mq.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*mq.Message, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *mq.Message); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*mq.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConsumer_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockConsumer_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockConsumer_Expecter) Read(_a0 interface{}) *MockConsumer_Read_Call {
	return &MockConsumer_Read_Call{Call: _e.mock.On("Read", _a0)}
}

func (_c *MockConsumer_Read_Call) Run(run func(_a0 context.Context)) *MockConsumer_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConsumer_Read_Call) Return(_a0 *mq.Message, _a1 error) *MockConsumer_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConsumer_Read_Call) RunAndReturn(run func(context.Context) (*mq.Message, error)) *MockConsumer_Read_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConsumer creates a new instance of MockConsumer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConsumer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConsumer {
	mock := &MockConsumer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
