// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockServerServiceInterface is an autogenerated mock type for the ServerServiceInterface type
type MockServerServiceInterface struct {
	mock.Mock
}

type MockServerServiceInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerServiceInterface) EXPECT() *MockServerServiceInterface_Expecter {
	return &MockServerServiceInterface_Expecter{mock: &_m.Mock}
}

// CreateServer provides a mock function with given fields: ctx, server
func (_m *MockServerServiceInterface) CreateServer(ctx context.Context, server *model.Server) (*model.Server, error) {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for CreateServer")
	}

	var r0 *model.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Server) (*model.Server, error)); ok {
		return rf(ctx, server)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Server) *model.Server); ok {
		r0 = rf(ctx, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Server) error); ok {
		r1 = rf(ctx, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerServiceInterface_CreateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateServer'
type MockServerServiceInterface_CreateServer_Call struct {
	*mock.Call
}

// CreateServer is a helper method to define mock.On call
//   - ctx context.Context
//   - server *model.Server
func (_e *MockServerServiceInterface_Expecter) CreateServer(ctx interface{}, server interface{}) *MockServerServiceInterface_CreateServer_Call {
	return &MockServerServiceInterface_CreateServer_Call{Call: _e.mock.On("CreateServer", ctx, server)}
}

func (_c *MockServerServiceInterface_CreateServer_Call) Run(run func(ctx context.Context, server *model.Server)) *MockServerServiceInterface_CreateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Server))
	})
	return _c
}

func (_c *MockServerServiceInterface_CreateServer_Call) Return(_a0 *model.Server, _a1 error) *MockServerServiceInterface_CreateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerServiceInterface_CreateServer_Call) RunAndReturn(run func(context.Context, *model.Server) (*model.Server, error)) *MockServerServiceInterface_CreateServer_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteServer provides a mock function with given fields: ctx, serverID
func (_m *MockServerServiceInterface) DeleteServer(ctx context.Context, serverID string) error {
	ret := _m.Called(ctx, serverID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServer")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, serverID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerServiceInterface_DeleteServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteServer'
type MockServerServiceInterface_DeleteServer_Call struct {
	*mock.Call
}

// DeleteServer is a helper method to define mock.On call
//   - ctx context.Context
//   - serverID string
func (_e *MockServerServiceInterface_Expecter) DeleteServer(ctx interface{}, serverID interface{}) *MockServerServiceInterface_DeleteServer_Call {
	return &MockServerServiceInterface_DeleteServer_Call{Call: _e.mock.On("DeleteServer", ctx, serverID)}
}

func (_c *MockServerServiceInterface_DeleteServer_Call) Run(run func(ctx context.Context, serverID string)) *MockServerServiceInterface_DeleteServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerServiceInterface_DeleteServer_Call) Return(_a0 error) *MockServerServiceInterface_DeleteServer_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerServiceInterface_DeleteServer_Call) RunAndReturn(run func(context.Context, string) error) *MockServerServiceInterface_DeleteServer_Call {
	_c.Call.Return(run)
	return _c
}

// ImportServer provides a mock function with given fields: ctx, serversData
func (_m *MockServerServiceInterface) ImportServer(ctx context.Context, serversData []model.ServerImport) (*model.CreateBatchServerResult, error) {
	ret := _m.Called(ctx, serversData)

	if len(ret) == 0 {
		panic("no return value specified for ImportServer")
	}

	var r0 *model.CreateBatchServerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []model.ServerImport) (*model.CreateBatchServerResult, error)); ok {
		return rf(ctx, serversData)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []model.ServerImport) *model.CreateBatchServerResult); ok {
		r0 = rf(ctx, serversData)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CreateBatchServerResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []model.ServerImport) error); ok {
		r1 = rf(ctx, serversData)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerServiceInterface_ImportServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportServer'
type MockServerServiceInterface_ImportServer_Call struct {
	*mock.Call
}

// ImportServer is a helper method to define mock.On call
//   - ctx context.Context
//   - serversData []model.ServerImport
func (_e *MockServerServiceInterface_Expecter) ImportServer(ctx interface{}, serversData interface{}) *MockServerServiceInterface_ImportServer_Call {
	return &MockServerServiceInterface_ImportServer_Call{Call: _e.mock.On("ImportServer", ctx, serversData)}
}

func (_c *MockServerServiceInterface_ImportServer_Call) Run(run func(ctx context.Context, serversData []model.ServerImport)) *MockServerServiceInterface_ImportServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.ServerImport))
	})
	return _c
}

func (_c *MockServerServiceInterface_ImportServer_Call) Return(_a0 *model.CreateBatchServerResult, _a1 error) *MockServerServiceInterface_ImportServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerServiceInterface_ImportServer_Call) RunAndReturn(run func(context.Context, []model.ServerImport) (*model.CreateBatchServerResult, error)) *MockServerServiceInterface_ImportServer_Call {
	_c.Call.Return(run)
	return _c
}

// ListServer provides a mock function with given fields: ctx, filter
func (_m *MockServerServiceInterface) ListServer(ctx context.Context, filter model.ListServerFilter) (*model.ListServerResult, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListServer")
	}

	var r0 *model.ListServerResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.ListServerFilter) (*model.ListServerResult, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.ListServerFilter) *model.ListServerResult); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ListServerResult)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.ListServerFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerServiceInterface_ListServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListServer'
type MockServerServiceInterface_ListServer_Call struct {
	*mock.Call
}

// ListServer is a helper method to define mock.On call
//   - ctx context.Context
//   - filter model.ListServerFilter
func (_e *MockServerServiceInterface_Expecter) ListServer(ctx interface{}, filter interface{}) *MockServerServiceInterface_ListServer_Call {
	return &MockServerServiceInterface_ListServer_Call{Call: _e.mock.On("ListServer", ctx, filter)}
}

func (_c *MockServerServiceInterface_ListServer_Call) Run(run func(ctx context.Context, filter model.ListServerFilter)) *MockServerServiceInterface_ListServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ListServerFilter))
	})
	return _c
}

func (_c *MockServerServiceInterface_ListServer_Call) Return(_a0 *model.ListServerResult, _a1 error) *MockServerServiceInterface_ListServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerServiceInterface_ListServer_Call) RunAndReturn(run func(context.Context, model.ListServerFilter) (*model.ListServerResult, error)) *MockServerServiceInterface_ListServer_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateServer provides a mock function with given fields: ctx, server
func (_m *MockServerServiceInterface) UpdateServer(ctx context.Context, server *model.Server) (*model.Server, error) {
	ret := _m.Called(ctx, server)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServer")
	}

	var r0 *model.Server
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Server) (*model.Server, error)); ok {
		return rf(ctx, server)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *model.Server) *model.Server); ok {
		r0 = rf(ctx, server)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Server)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *model.Server) error); ok {
		r1 = rf(ctx, server)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockServerServiceInterface_UpdateServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateServer'
type MockServerServiceInterface_UpdateServer_Call struct {
	*mock.Call
}

// UpdateServer is a helper method to define mock.On call
//   - ctx context.Context
//   - server *model.Server
func (_e *MockServerServiceInterface_Expecter) UpdateServer(ctx interface{}, server interface{}) *MockServerServiceInterface_UpdateServer_Call {
	return &MockServerServiceInterface_UpdateServer_Call{Call: _e.mock.On("UpdateServer", ctx, server)}
}

func (_c *MockServerServiceInterface_UpdateServer_Call) Run(run func(ctx context.Context, server *model.Server)) *MockServerServiceInterface_UpdateServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*model.Server))
	})
	return _c
}

func (_c *MockServerServiceInterface_UpdateServer_Call) Return(_a0 *model.Server, _a1 error) *MockServerServiceInterface_UpdateServer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockServerServiceInterface_UpdateServer_Call) RunAndReturn(run func(context.Context, *model.Server) (*model.Server, error)) *MockServerServiceInterface_UpdateServer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerServiceInterface creates a new instance of MockServerServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerServiceInterface {
	mock := &MockServerServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
