// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockServerMetadataCacheInterface is an autogenerated mock type for the ServerMetadataCacheInterface type
type MockServerMetadataCacheInterface struct {
	mock.Mock
}

type MockServerMetadataCacheInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerMetadataCacheInterface) EXPECT() *MockServerMetadataCacheInterface_Expecter {
	return &MockServerMetadataCacheInterface_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function with given fields: ctx, s
func (_m *MockServerMetadataCacheInterface) BatchCreate(ctx context.Context, s []model.ServerMetadata) {
	_m.Called(ctx, s)
}

// MockServerMetadataCacheInterface_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type MockServerMetadataCacheInterface_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx context.Context
//   - s []model.ServerMetadata
func (_e *MockServerMetadataCacheInterface_Expecter) BatchCreate(ctx interface{}, s interface{}) *MockServerMetadataCacheInterface_BatchCreate_Call {
	return &MockServerMetadataCacheInterface_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, s)}
}

func (_c *MockServerMetadataCacheInterface_BatchCreate_Call) Run(run func(ctx context.Context, s []model.ServerMetadata)) *MockServerMetadataCacheInterface_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.ServerMetadata))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_BatchCreate_Call) Return() *MockServerMetadataCacheInterface_BatchCreate_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerMetadataCacheInterface_BatchCreate_Call) RunAndReturn(run func(context.Context, []model.ServerMetadata)) *MockServerMetadataCacheInterface_BatchCreate_Call {
	_c.Run(run)
	return _c
}

// BatchUpdateHeartbeat provides a mock function with given fields: ctx, s
func (_m *MockServerMetadataCacheInterface) BatchUpdateHeartbeat(ctx context.Context, s []model.ServerMetadata) {
	_m.Called(ctx, s)
}

// MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdateHeartbeat'
type MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call struct {
	*mock.Call
}

// BatchUpdateHeartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - s []model.ServerMetadata
func (_e *MockServerMetadataCacheInterface_Expecter) BatchUpdateHeartbeat(ctx interface{}, s interface{}) *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call {
	return &MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call{Call: _e.mock.On("BatchUpdateHeartbeat", ctx, s)}
}

func (_c *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call) Run(run func(ctx context.Context, s []model.ServerMetadata)) *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]model.ServerMetadata))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call) Return() *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call) RunAndReturn(run func(context.Context, []model.ServerMetadata)) *MockServerMetadataCacheInterface_BatchUpdateHeartbeat_Call {
	_c.Run(run)
	return _c
}

// Create provides a mock function with given fields: ctx, s
func (_m *MockServerMetadataCacheInterface) Create(ctx context.Context, s model.ServerMetadata) {
	_m.Called(ctx, s)
}

// MockServerMetadataCacheInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockServerMetadataCacheInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.ServerMetadata
func (_e *MockServerMetadataCacheInterface_Expecter) Create(ctx interface{}, s interface{}) *MockServerMetadataCacheInterface_Create_Call {
	return &MockServerMetadataCacheInterface_Create_Call{Call: _e.mock.On("Create", ctx, s)}
}

func (_c *MockServerMetadataCacheInterface_Create_Call) Run(run func(ctx context.Context, s model.ServerMetadata)) *MockServerMetadataCacheInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ServerMetadata))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_Create_Call) Return() *MockServerMetadataCacheInterface_Create_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerMetadataCacheInterface_Create_Call) RunAndReturn(run func(context.Context, model.ServerMetadata)) *MockServerMetadataCacheInterface_Create_Call {
	_c.Run(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, s
func (_m *MockServerMetadataCacheInterface) Delete(ctx context.Context, s string) {
	_m.Called(ctx, s)
}

// MockServerMetadataCacheInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockServerMetadataCacheInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - s string
func (_e *MockServerMetadataCacheInterface_Expecter) Delete(ctx interface{}, s interface{}) *MockServerMetadataCacheInterface_Delete_Call {
	return &MockServerMetadataCacheInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, s)}
}

func (_c *MockServerMetadataCacheInterface_Delete_Call) Run(run func(ctx context.Context, s string)) *MockServerMetadataCacheInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_Delete_Call) Return() *MockServerMetadataCacheInterface_Delete_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerMetadataCacheInterface_Delete_Call) RunAndReturn(run func(context.Context, string)) *MockServerMetadataCacheInterface_Delete_Call {
	_c.Run(run)
	return _c
}

// List provides a mock function with given fields: ctx
func (_m *MockServerMetadataCacheInterface) List(ctx context.Context) []model.ServerMetadata {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.ServerMetadata
	if rf, ok := ret.Get(0).(func(context.Context) []model.ServerMetadata); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ServerMetadata)
		}
	}

	return r0
}

// MockServerMetadataCacheInterface_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockServerMetadataCacheInterface_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerMetadataCacheInterface_Expecter) List(ctx interface{}) *MockServerMetadataCacheInterface_List_Call {
	return &MockServerMetadataCacheInterface_List_Call{Call: _e.mock.On("List", ctx)}
}

func (_c *MockServerMetadataCacheInterface_List_Call) Run(run func(ctx context.Context)) *MockServerMetadataCacheInterface_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_List_Call) Return(_a0 []model.ServerMetadata) *MockServerMetadataCacheInterface_List_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerMetadataCacheInterface_List_Call) RunAndReturn(run func(context.Context) []model.ServerMetadata) *MockServerMetadataCacheInterface_List_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function with given fields: ctx
func (_m *MockServerMetadataCacheInterface) Sync(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerMetadataCacheInterface_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockServerMetadataCacheInterface_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockServerMetadataCacheInterface_Expecter) Sync(ctx interface{}) *MockServerMetadataCacheInterface_Sync_Call {
	return &MockServerMetadataCacheInterface_Sync_Call{Call: _e.mock.On("Sync", ctx)}
}

func (_c *MockServerMetadataCacheInterface_Sync_Call) Run(run func(ctx context.Context)) *MockServerMetadataCacheInterface_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_Sync_Call) Return(_a0 error) *MockServerMetadataCacheInterface_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerMetadataCacheInterface_Sync_Call) RunAndReturn(run func(context.Context) error) *MockServerMetadataCacheInterface_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, s
func (_m *MockServerMetadataCacheInterface) Update(ctx context.Context, s model.ServerMetadata) {
	_m.Called(ctx, s)
}

// MockServerMetadataCacheInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockServerMetadataCacheInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s model.ServerMetadata
func (_e *MockServerMetadataCacheInterface_Expecter) Update(ctx interface{}, s interface{}) *MockServerMetadataCacheInterface_Update_Call {
	return &MockServerMetadataCacheInterface_Update_Call{Call: _e.mock.On("Update", ctx, s)}
}

func (_c *MockServerMetadataCacheInterface_Update_Call) Run(run func(ctx context.Context, s model.ServerMetadata)) *MockServerMetadataCacheInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.ServerMetadata))
	})
	return _c
}

func (_c *MockServerMetadataCacheInterface_Update_Call) Return() *MockServerMetadataCacheInterface_Update_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockServerMetadataCacheInterface_Update_Call) RunAndReturn(run func(context.Context, model.ServerMetadata)) *MockServerMetadataCacheInterface_Update_Call {
	_c.Run(run)
	return _c
}

// NewMockServerMetadataCacheInterface creates a new instance of MockServerMetadataCacheInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerMetadataCacheInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerMetadataCacheInterface {
	mock := &MockServerMetadataCacheInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
