// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/LeHuuHai/server-management/internal/model"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockReportAggregator is an autogenerated mock type for the ReportAggregator type
type MockReportAggregator struct {
	mock.Mock
}

type MockReportAggregator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportAggregator) EXPECT() *MockReportAggregator_Expecter {
	return &MockReportAggregator_Expecter{mock: &_m.Mock}
}

// Aggregation provides a mock function with given fields: ctx, from, to
func (_m *MockReportAggregator) Aggregation(ctx context.Context, from time.Time, to time.Time) ([]model.ServerUptimeAgg, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for Aggregation")
	}

	var r0 []model.ServerUptimeAgg
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) ([]model.ServerUptimeAgg, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time, time.Time) []model.ServerUptimeAgg); ok {
		r0 = rf(ctx, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ServerUptimeAgg)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time, time.Time) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockReportAggregator_Aggregation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Aggregation'
type MockReportAggregator_Aggregation_Call struct {
	*mock.Call
}

// Aggregation is a helper method to define mock.On call
//   - ctx context.Context
//   - from time.Time
//   - to time.Time
func (_e *MockReportAggregator_Expecter) Aggregation(ctx interface{}, from interface{}, to interface{}) *MockReportAggregator_Aggregation_Call {
	return &MockReportAggregator_Aggregation_Call{Call: _e.mock.On("Aggregation", ctx, from, to)}
}

func (_c *MockReportAggregator_Aggregation_Call) Run(run func(ctx context.Context, from time.Time, to time.Time)) *MockReportAggregator_Aggregation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time), args[2].(time.Time))
	})
	return _c
}

func (_c *MockReportAggregator_Aggregation_Call) Return(_a0 []model.ServerUptimeAgg, _a1 error) *MockReportAggregator_Aggregation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportAggregator_Aggregation_Call) RunAndReturn(run func(context.Context, time.Time, time.Time) ([]model.ServerUptimeAgg, error)) *MockReportAggregator_Aggregation_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportAggregator creates a new instance of MockReportAggregator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportAggregator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportAggregator {
	mock := &MockReportAggregator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
