// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"

	model "github.com/LeHuuHai/server-management/internal/model"
)

// MockServerExporter is an autogenerated mock type for the ServerExporter type
type MockServerExporter struct {
	mock.Mock
}

type MockServerExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockServerExporter) EXPECT() *MockServerExporter_Expecter {
	return &MockServerExporter_Expecter{mock: &_m.Mock}
}

// ContentType provides a mock function with no fields
func (_m *MockServerExporter) ContentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServerExporter_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type MockServerExporter_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *MockServerExporter_Expecter) ContentType() *MockServerExporter_ContentType_Call {
	return &MockServerExporter_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *MockServerExporter_ContentType_Call) Run(run func()) *MockServerExporter_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerExporter_ContentType_Call) Return(_a0 string) *MockServerExporter_ContentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerExporter_ContentType_Call) RunAndReturn(run func() string) *MockServerExporter_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function with given fields: ctx, writer, data
func (_m *MockServerExporter) Export(ctx context.Context, writer io.Writer, data []model.Server) error {
	ret := _m.Called(ctx, writer, data)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Writer, []model.Server) error); ok {
		r0 = rf(ctx, writer, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockServerExporter_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockServerExporter_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - writer io.Writer
//   - data []model.Server
func (_e *MockServerExporter_Expecter) Export(ctx interface{}, writer interface{}, data interface{}) *MockServerExporter_Export_Call {
	return &MockServerExporter_Export_Call{Call: _e.mock.On("Export", ctx, writer, data)}
}

func (_c *MockServerExporter_Export_Call) Run(run func(ctx context.Context, writer io.Writer, data []model.Server)) *MockServerExporter_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Writer), args[2].([]model.Server))
	})
	return _c
}

func (_c *MockServerExporter_Export_Call) Return(_a0 error) *MockServerExporter_Export_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerExporter_Export_Call) RunAndReturn(run func(context.Context, io.Writer, []model.Server) error) *MockServerExporter_Export_Call {
	_c.Call.Return(run)
	return _c
}

// FileType provides a mock function with no fields
func (_m *MockServerExporter) FileType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FileType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockServerExporter_FileType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileType'
type MockServerExporter_FileType_Call struct {
	*mock.Call
}

// FileType is a helper method to define mock.On call
func (_e *MockServerExporter_Expecter) FileType() *MockServerExporter_FileType_Call {
	return &MockServerExporter_FileType_Call{Call: _e.mock.On("FileType")}
}

func (_c *MockServerExporter_FileType_Call) Run(run func()) *MockServerExporter_FileType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockServerExporter_FileType_Call) Return(_a0 string) *MockServerExporter_FileType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockServerExporter_FileType_Call) RunAndReturn(run func() string) *MockServerExporter_FileType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockServerExporter creates a new instance of MockServerExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockServerExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockServerExporter {
	mock := &MockServerExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
