// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	io "io"

	mock "github.com/stretchr/testify/mock"

	model "github.com/LeHuuHai/server-management/internal/model"
)

// MockReportServerExporter is an autogenerated mock type for the ReportServerExporter type
type MockReportServerExporter struct {
	mock.Mock
}

type MockReportServerExporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportServerExporter) EXPECT() *MockReportServerExporter_Expecter {
	return &MockReportServerExporter_Expecter{mock: &_m.Mock}
}

// ContentType provides a mock function with no fields
func (_m *MockReportServerExporter) ContentType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ContentType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockReportServerExporter_ContentType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ContentType'
type MockReportServerExporter_ContentType_Call struct {
	*mock.Call
}

// ContentType is a helper method to define mock.On call
func (_e *MockReportServerExporter_Expecter) ContentType() *MockReportServerExporter_ContentType_Call {
	return &MockReportServerExporter_ContentType_Call{Call: _e.mock.On("ContentType")}
}

func (_c *MockReportServerExporter_ContentType_Call) Run(run func()) *MockReportServerExporter_ContentType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportServerExporter_ContentType_Call) Return(_a0 string) *MockReportServerExporter_ContentType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportServerExporter_ContentType_Call) RunAndReturn(run func() string) *MockReportServerExporter_ContentType_Call {
	_c.Call.Return(run)
	return _c
}

// Export provides a mock function with given fields: ctx, writer, data
func (_m *MockReportServerExporter) Export(ctx context.Context, writer io.Writer, data []model.ServerUptimeAgg) error {
	ret := _m.Called(ctx, writer, data)

	if len(ret) == 0 {
		panic("no return value specified for Export")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, io.Writer, []model.ServerUptimeAgg) error); ok {
		r0 = rf(ctx, writer, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReportServerExporter_Export_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Export'
type MockReportServerExporter_Export_Call struct {
	*mock.Call
}

// Export is a helper method to define mock.On call
//   - ctx context.Context
//   - writer io.Writer
//   - data []model.ServerUptimeAgg
func (_e *MockReportServerExporter_Expecter) Export(ctx interface{}, writer interface{}, data interface{}) *MockReportServerExporter_Export_Call {
	return &MockReportServerExporter_Export_Call{Call: _e.mock.On("Export", ctx, writer, data)}
}

func (_c *MockReportServerExporter_Export_Call) Run(run func(ctx context.Context, writer io.Writer, data []model.ServerUptimeAgg)) *MockReportServerExporter_Export_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(io.Writer), args[2].([]model.ServerUptimeAgg))
	})
	return _c
}

func (_c *MockReportServerExporter_Export_Call) Return(_a0 error) *MockReportServerExporter_Export_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportServerExporter_Export_Call) RunAndReturn(run func(context.Context, io.Writer, []model.ServerUptimeAgg) error) *MockReportServerExporter_Export_Call {
	_c.Call.Return(run)
	return _c
}

// FileType provides a mock function with no fields
func (_m *MockReportServerExporter) FileType() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for FileType")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockReportServerExporter_FileType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileType'
type MockReportServerExporter_FileType_Call struct {
	*mock.Call
}

// FileType is a helper method to define mock.On call
func (_e *MockReportServerExporter_Expecter) FileType() *MockReportServerExporter_FileType_Call {
	return &MockReportServerExporter_FileType_Call{Call: _e.mock.On("FileType")}
}

func (_c *MockReportServerExporter_FileType_Call) Run(run func()) *MockReportServerExporter_FileType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockReportServerExporter_FileType_Call) Return(_a0 string) *MockReportServerExporter_FileType_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReportServerExporter_FileType_Call) RunAndReturn(run func() string) *MockReportServerExporter_FileType_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportServerExporter creates a new instance of MockReportServerExporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportServerExporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportServerExporter {
	mock := &MockReportServerExporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
