// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "apiKeyAuth.Scopes"
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ServerStatus.
const (
	OFF     ServerStatus = "OFF"
	ON      ServerStatus = "ON"
	UNKNOWN ServerStatus = "UNKNOWN"
)

// Valid indicates whether the value is a known member of the ServerStatus enum.
func (e ServerStatus) Valid() bool {
	switch e {
	case OFF:
		return true
	case ON:
		return true
	case UNKNOWN:
		return true
	default:
		return false
	}
}

// CreateServerRequest defines model for CreateServerRequest.
type CreateServerRequest struct {
	Ipv4       string `json:"ipv4"`
	ServerId   string `json:"server_id"`
	ServerName string `json:"server_name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *string `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// GetListServersResponse defines model for GetListServersResponse.
type GetListServersResponse struct {
	Items *[]Server `json:"items,omitempty"`
	Total *int      `json:"total,omitempty"`
}

// ImportServerResponse defines model for ImportServerResponse.
type ImportServerResponse struct {
	IdFailed     []string `json:"id_failed"`
	IdSuccess    []string `json:"id_success"`
	TotalFailed  int      `json:"total_failed"`
	TotalSuccess int      `json:"total_success"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// ReportServerRequest defines model for ReportServerRequest.
type ReportServerRequest struct {
	From      time.Time             `json:"from"`
	Receivers []openapi_types.Email `json:"receivers"`
	To        time.Time             `json:"to"`
}

// Server defines model for Server.
type Server struct {
	CreatedAt         *time.Time   `json:"created_at,omitempty"`
	Ipv4              string       `json:"ipv4"`
	LastPingAt        *time.Time   `json:"last_ping_at,omitempty"`
	MetadataUpdatedAt *time.Time   `json:"metadata_updated_at,omitempty"`
	ServerId          string       `json:"server_id"`
	ServerName        string       `json:"server_name"`
	Status            ServerStatus `json:"status"`
}

// ServerStatus defines model for Server.Status.
type ServerStatus string

// UpdateServerRequest defines model for UpdateServerRequest.
type UpdateServerRequest struct {
	Ipv4       *string `json:"ipv4,omitempty"`
	ServerName *string `json:"server_name,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// apiKeyAuthContextKey is the context key for apiKeyAuth security scheme
type apiKeyAuthContextKey string

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// GetListServersParams defines parameters for GetListServers.
type GetListServersParams struct {
	From      int    `form:"from" json:"from"`
	To        int    `form:"to" json:"to"`
	SortField string `form:"sort_field" json:"sort_field"`
	Desc      bool   `form:"desc" json:"desc"`
}

// ExportServersParams defines parameters for ExportServers.
type ExportServersParams struct {
	From      int    `form:"from" json:"from"`
	To        int    `form:"to" json:"to"`
	SortField string `form:"sort_field" json:"sort_field"`
	Desc      bool   `form:"desc" json:"desc"`
}

// ImportServerMultipartBody defines parameters for ImportServer.
type ImportServerMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = CreateServerRequest

// ImportServerMultipartRequestBody defines body for ImportServer for multipart/form-data ContentType.
type ImportServerMultipartRequestBody ImportServerMultipartBody

// GenerateServerReportJSONRequestBody defines body for GenerateServerReport for application/json ContentType.
type GenerateServerReportJSONRequestBody = ReportServerRequest

// UpdateServerJSONRequestBody defines body for UpdateServer for application/json ContentType.
type UpdateServerJSONRequestBody = UpdateServerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login
	// (POST /auth/login)
	Login(c *gin.Context)
	// Refresh token
	// (POST /auth/refresh)
	RefreshToken(c *gin.Context)
	// Download report file
	// (GET /report/{filename})
	GetReportFile(c *gin.Context, filename string)
	// Get list servers
	// (GET /servers)
	GetListServers(c *gin.Context, params GetListServersParams)
	// Create server
	// (POST /servers)
	CreateServer(c *gin.Context)
	// Export servers
	// (GET /servers/export)
	ExportServers(c *gin.Context, params ExportServersParams)
	// Import server
	// (POST /servers/import)
	ImportServer(c *gin.Context)
	// Generate server report
	// (POST /servers/report)
	GenerateServerReport(c *gin.Context)
	// Delete server
	// (DELETE /servers/{server_id})
	DeleteServer(c *gin.Context, serverId string)
	// Update server
	// (PATCH /servers/{server_id})
	UpdateServer(c *gin.Context, serverId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// GetReportFile operation middleware
func (siw *ServerInterfaceWrapper) GetReportFile(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameterWithOptions("simple", "filename", c.Param("filename"), &filename, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filename: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(ApiKeyAuthScopes), []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReportFile(c, filename)
}

// GetListServers operation middleware
func (siw *ServerInterfaceWrapper) GetListServers(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{"server:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListServersParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "sort_field" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "sort_field", c.Request.URL.Query(), &params.SortField, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_field: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "desc" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "desc", c.Request.URL.Query(), &params.Desc, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter desc: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetListServers(c, params)
}

// CreateServer operation middleware
func (siw *ServerInterfaceWrapper) CreateServer(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{"server:create"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateServer(c)
}

// ExportServers operation middleware
func (siw *ServerInterfaceWrapper) ExportServers(c *gin.Context) {

	var err error
	_ = err

	c.Set(string(BearerAuthScopes), []string{"server:export"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportServersParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", c.Request.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", c.Request.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "sort_field" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "sort_field", c.Request.URL.Query(), &params.SortField, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_field: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "desc" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "desc", c.Request.URL.Query(), &params.Desc, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter desc: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportServers(c, params)
}

// ImportServer operation middleware
func (siw *ServerInterfaceWrapper) ImportServer(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{"server:import"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ImportServer(c)
}

// GenerateServerReport operation middleware
func (siw *ServerInterfaceWrapper) GenerateServerReport(c *gin.Context) {

	c.Set(string(BearerAuthScopes), []string{"server:report"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateServerReport(c)
}

// DeleteServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteServer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId string

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{"server:delete"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteServer(c, serverId)
}

// UpdateServer operation middleware
func (siw *ServerInterfaceWrapper) UpdateServer(c *gin.Context) {

	var err error
	_ = err

	// ------------- Path parameter "server_id" -------------
	var serverId string

	err = runtime.BindStyledParameterWithOptions("simple", "server_id", c.Param("server_id"), &serverId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(string(BearerAuthScopes), []string{"server:update"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateServer(c, serverId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	router.GET(options.BaseURL+"/report/:filename", wrapper.GetReportFile)
	router.GET(options.BaseURL+"/servers", wrapper.GetListServers)
	router.POST(options.BaseURL+"/servers", wrapper.CreateServer)
	router.GET(options.BaseURL+"/servers/export", wrapper.ExportServers)
	router.POST(options.BaseURL+"/servers/import", wrapper.ImportServer)
	router.POST(options.BaseURL+"/servers/report", wrapper.GenerateServerReport)
	router.DELETE(options.BaseURL+"/servers/:server_id", wrapper.DeleteServer)
	router.PATCH(options.BaseURL+"/servers/:server_id", wrapper.UpdateServer)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type Login500JSONResponse struct{ InternalErrorJSONResponse }

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse LoginResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshToken500JSONResponse struct{ InternalErrorJSONResponse }

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetReportFileRequestObject struct {
	Filename string `json:"filename"`
}

type GetReportFileResponseObject interface {
	VisitGetReportFileResponse(w http.ResponseWriter) error
}

type GetReportFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetReportFile200ApplicationoctetStreamResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetReportFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetReportFile401JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetReportFile403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetReportFile403JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetReportFile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetReportFile404JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetReportFile500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetReportFile500JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetListServersRequestObject struct {
	Params GetListServersParams
}

type GetListServersResponseObject interface {
	VisitGetListServersResponse(w http.ResponseWriter) error
}

type GetListServers200JSONResponse GetListServersResponse

func (response GetListServers200JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetListServers400JSONResponse struct{ BadRequestJSONResponse }

func (response GetListServers400JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetListServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetListServers401JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetListServers403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetListServers403JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GetListServers500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetListServers500JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServerRequestObject struct {
	Body *CreateServerJSONRequestBody
}

type CreateServerResponseObject interface {
	VisitCreateServerResponse(w http.ResponseWriter) error
}

type CreateServer201JSONResponse Server

func (response CreateServer201JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateServer400JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateServer401JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateServer403JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer409JSONResponse struct{ ConflictJSONResponse }

func (response CreateServer409JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type CreateServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateServer500JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ExportServersRequestObject struct {
	Params ExportServersParams
}

type ExportServersResponseObject interface {
	VisitExportServersResponse(w http.ResponseWriter) error
}

type ExportServers200ResponseHeaders struct {
	ContentDisposition *string
}

type ExportServers200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	Headers       ExportServers200ResponseHeaders
	ContentLength int64
}

func (response ExportServers200ApplicationoctetStreamResponse) VisitExportServersResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportServers400JSONResponse struct{ BadRequestJSONResponse }

func (response ExportServers400JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ExportServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExportServers401JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ExportServers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ExportServers403JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ExportServers500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportServers500JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ImportServerRequestObject struct {
	Body *multipart.Reader
}

type ImportServerResponseObject interface {
	VisitImportServerResponse(w http.ResponseWriter) error
}

type ImportServer200JSONResponse ImportServerResponse

func (response ImportServer200JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ImportServer400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportServer400JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ImportServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ImportServer401JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ImportServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response ImportServer403JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type ImportServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response ImportServer500JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateServerReportRequestObject struct {
	Body *GenerateServerReportJSONRequestBody
}

type GenerateServerReportResponseObject interface {
	VisitGenerateServerReportResponse(w http.ResponseWriter) error
}

type GenerateServerReport202Response struct {
}

func (response GenerateServerReport202Response) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type GenerateServerReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GenerateServerReport400JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateServerReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GenerateServerReport401JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateServerReport403JSONResponse struct{ ForbiddenJSONResponse }

func (response GenerateServerReport403JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type GenerateServerReport500JSONResponse struct{ InternalErrorJSONResponse }

func (response GenerateServerReport500JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServerRequestObject struct {
	ServerId string `json:"server_id"`
}

type DeleteServerResponseObject interface {
	VisitDeleteServerResponse(w http.ResponseWriter) error
}

type DeleteServer204Response struct {
}

func (response DeleteServer204Response) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteServer401JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteServer403JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServer404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteServer404JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteServer500JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServerRequestObject struct {
	ServerId string `json:"server_id"`
	Body     *UpdateServerJSONRequestBody
}

type UpdateServerResponseObject interface {
	VisitUpdateServerResponse(w http.ResponseWriter) error
}

type UpdateServer200JSONResponse Server

func (response UpdateServer200JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateServer400JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateServer401JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateServer403JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateServer404JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateServer500JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Refresh token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Download report file
	// (GET /report/{filename})
	GetReportFile(ctx context.Context, request GetReportFileRequestObject) (GetReportFileResponseObject, error)
	// Get list servers
	// (GET /servers)
	GetListServers(ctx context.Context, request GetListServersRequestObject) (GetListServersResponseObject, error)
	// Create server
	// (POST /servers)
	CreateServer(ctx context.Context, request CreateServerRequestObject) (CreateServerResponseObject, error)
	// Export servers
	// (GET /servers/export)
	ExportServers(ctx context.Context, request ExportServersRequestObject) (ExportServersResponseObject, error)
	// Import server
	// (POST /servers/import)
	ImportServer(ctx context.Context, request ImportServerRequestObject) (ImportServerResponseObject, error)
	// Generate server report
	// (POST /servers/report)
	GenerateServerReport(ctx context.Context, request GenerateServerReportRequestObject) (GenerateServerReportResponseObject, error)
	// Delete server
	// (DELETE /servers/{server_id})
	DeleteServer(ctx context.Context, request DeleteServerRequestObject) (DeleteServerResponseObject, error)
	// Update server
	// (PATCH /servers/{server_id})
	UpdateServer(ctx context.Context, request UpdateServerRequestObject) (UpdateServerResponseObject, error)
}

type StrictHandlerFunc func(ctx *gin.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictGinServerOptions struct {
	// RequestErrorHandlerFunc is called when a request cannot be parsed or
	// decoded. It is invoked for JSON bind failures, form parse/bind errors,
	// multipart reader errors, media type parse errors, missing multipart
	// boundaries, and request body read errors. The default returns 400.
	RequestErrorHandlerFunc func(ctx *gin.Context, err error)
	// HandlerErrorFunc is called when the application handler (or any
	// middleware wrapping it) returns a non-nil error. The default returns 500.
	HandlerErrorFunc func(ctx *gin.Context, err error)
	// ResponseErrorHandlerFunc is called when the response object fails to
	// serialize (Visit*Response returns an error) or when the handler returns
	// an unexpected response type. The default returns 500.
	ResponseErrorHandlerFunc func(ctx *gin.Context, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictGinServerOptions{
		RequestErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		},
		HandlerErrorFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
		ResponseErrorHandlerFunc: func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictGinServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusBadRequest, gin.H{"msg": err.Error()})
		}
	}
	if options.HandlerErrorFunc == nil {
		options.HandlerErrorFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(ctx *gin.Context, err error) {
			ctx.JSON(http.StatusInternalServerError, gin.H{"msg": err.Error()})
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictGinServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReportFile operation middleware
func (sh *strictHandler) GetReportFile(ctx *gin.Context, filename string) {
	var request GetReportFileRequestObject

	request.Filename = filename

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReportFile(ctx, request.(GetReportFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReportFile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetReportFileResponseObject); ok {
		if err := validResponse.VisitGetReportFileResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetListServers operation middleware
func (sh *strictHandler) GetListServers(ctx *gin.Context, params GetListServersParams) {
	var request GetListServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetListServers(ctx, request.(GetListServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetListServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GetListServersResponseObject); ok {
		if err := validResponse.VisitGetListServersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateServer operation middleware
func (sh *strictHandler) CreateServer(ctx *gin.Context) {
	var request CreateServerRequestObject

	var body CreateServerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServer(ctx, request.(CreateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(CreateServerResponseObject); ok {
		if err := validResponse.VisitCreateServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportServers operation middleware
func (sh *strictHandler) ExportServers(ctx *gin.Context, params ExportServersParams) {
	var request ExportServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ExportServers(ctx, request.(ExportServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ExportServersResponseObject); ok {
		if err := validResponse.VisitExportServersResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportServer operation middleware
func (sh *strictHandler) ImportServer(ctx *gin.Context) {
	var request ImportServerRequestObject

	if reader, err := ctx.Request.MultipartReader(); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	} else {
		request.Body = reader
	}

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ImportServer(ctx, request.(ImportServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(ImportServerResponseObject); ok {
		if err := validResponse.VisitImportServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateServerReport operation middleware
func (sh *strictHandler) GenerateServerReport(ctx *gin.Context) {
	var request GenerateServerReportRequestObject

	var body GenerateServerReportJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateServerReport(ctx, request.(GenerateServerReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateServerReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(GenerateServerReportResponseObject); ok {
		if err := validResponse.VisitGenerateServerReportResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteServer operation middleware
func (sh *strictHandler) DeleteServer(ctx *gin.Context, serverId string) {
	var request DeleteServerRequestObject

	request.ServerId = serverId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteServer(ctx, request.(DeleteServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(DeleteServerResponseObject); ok {
		if err := validResponse.VisitDeleteServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateServer operation middleware
func (sh *strictHandler) UpdateServer(ctx *gin.Context, serverId string) {
	var request UpdateServerRequestObject

	request.ServerId = serverId

	var body UpdateServerJSONRequestBody
	if err := ctx.ShouldBindJSON(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(ctx, err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateServer(ctx, request.(UpdateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		sh.options.HandlerErrorFunc(ctx, err)
	} else if validResponse, ok := response.(UpdateServerResponseObject); ok {
		if err := validResponse.VisitUpdateServerResponse(ctx.Writer); err != nil {
			sh.options.ResponseErrorHandlerFunc(ctx, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(ctx, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fnbbts4E34Vgf9/qcRO6wW6XuxFekiQbTct0hZdIDUMRhrb7EqkSo7aeAO9+4IH2ZRMOXbrOFm0V4kl",
	"cmY43zcHjm5IIvJCcOCoyPCGSFCF4ArMj6c0vYDPJSjUvxLBEbj5lxZFxhKKTPDeJyW4fqaSGeRU//d/",
	"CRMyJP/rLUX37FvVeyGlkBdOCamqKiYpqESyQgsjQ60zkk5pFZNngk8yluzRgAtQopQJREmtuorJiZBX",
	"LE2B78+OpcoqJmccQXKamV37s6FWGymQX0BGYNRXMTkXeCJKnt4DLFxgNDG6q5i857TEmZDsH9ijLQ2t",
	"+rXbqQU/k0AR3hp/ecFTSFGARGYDixVfBvrvRMicIhnaBzHBeQFkSBRKxqf6fNbvY2YO1/WW0xwC76uY",
	"6EBiUrvm0hPV3Bhb5aOFdnH1CSzrm45YOUUiUgjalYNSdBp+52I7fKQqYMQp4Cum0HpUdVvDEPLmP+sw",
	"tuLIUiGVks7Nb4E082xjHGGql4aMO8sLIbFGu9O0dDyhLLMUXZi34pq2JSwdqzJJQKnt9pkTeBrbB6lX",
	"eMIDZ/W501zfsKylLvYOG6LUKzFlvDMuCqrUVyHTRmwsHgbio1Q6P21C/8XKeClwjYFdUFJz6jGKv20t",
	"CPB7IkHNOleEWHRh97zTWzp9s4Fg/7zN5aOgVp+7HVonUuQNNFKKcIDMODJw+ASYDtMGYRd7IacsC+1b",
	"ZfCmOlunNuaa/b4xodO7BLCa1Ez+TscUNz/2xuk8owrHBePTrcTngDSlSMdlkW5t2/dUkJgopFgavwAv",
	"c+3h1+ckJq9PTkhM3p+/PH/94dxz77eVnoWaEE7vzZl3XE+7U0ZLv9mSlJLh/K2uHC4JFOwlzI9LnBnl",
	"uiWYAU1BkphY0eSvg+M3ZwcvYb60wu7SVlwBlSDr/fbXSW36Hx/eEddR6F327VLKDLGwPQnjExMmzd7k",
	"+M1ZNBEyyimnU8anrnUziZphpkVYZ0Z/6hWQA8fo+M0ZiYleZoUcHfYP+9pSUQCnBSND8viwf/jYJE+c",
	"GSf0dA/Uy3S6NIAIC4yGxTRdZykZ2mxKFlX/qUjnO2vTGqWkanIOZQnmgXebedTv71p3d4toFkSuSE7K",
	"TDtz0D/qkrswtNfsLWPyi7V6/abm9cCwtsxzKuceBEinSgejFk9Geo1F0BWKbgz96nRHUIYK4END1BgX",
	"OW9ZbO4HUOesCB0gAWClKe29mwnLQCekSmucQgDcU0DbB5ywzPZGkuaApoRfutymQ36Z2WqZpI1O7Hm6",
	"nVhHWyEnEgQ8UCiB5k0EFwn+inHtjdXKs4Lbc/GVZ8JMFfQ5I22/F5jZ/JuRHPQf376pcY0f9Ae371jc",
	"rb+DLK5mGQz9anU50lAsuRRyjkcpQwpLqbqMrCGSd03rYNLnEgxoNZVst9ZNoxQmtMyQDPtx4IoSFup6",
	"v1tFHm0hUwmJ4wmDLN2K9R3SND83kXMlRAaUbx0+2yW+jvt1IJJOAaOMKaxbikAUbcBWb6i4v8DbRRz5",
	"XVvd0w4l0JS0gqrtJy+g3K1jVMUdxdYfH91RsQ1NqDYqtkc7M6GevqxyzPWm7hb2sEk16P96+45n3hT5",
	"zlho3dXmoQXasTBEQi+v9+BaF4DO9P7iejks+Jnd7zO777Q5srCGE3rsLrV2rG2NOXjOVCEUs9vbd0+K",
	"SJOZvlH+FtVt4u8fHUnV4XWmrj8Sss6n1Y9ZRVzwteK3Cc5tAczyOoDDlcUfVa+tLHmZISuoxJ4m1EFK",
	"kTZ51poQ6h5xI/a1RnWmt1yduOz11hec34c+hJl1EU0SKB58XbozmjqKtWjqfLNZmbH3jG6WngLXPxft",
	"iVl9V0OH1fn3RvR7tJr5rKxoaq1ngkefSygh/dki6xY5xJoa6PrTsqyhXkufm8UoubIgZICwyqLn5vki",
	"190+1PAn1N8z1RisUsPakv5QI4cgDxxY7QmEebome5iRczJbBdn/MnDXIO8++4S+a+y5+HXfwqxx/6Xs",
	"9XBobj/StWluPbquSK4VbqXVI7jLG1LKzH0MGvZ6mUhoNhMKh0/6T/pEr3Xyb2ru11iPqn8DAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
