// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	strictgin "github.com/oapi-codegen/runtime/strictmiddleware/gin"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "apiKeyAuth.Scopes"
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for ServerStatus.
const (
	OFF     ServerStatus = "OFF"
	ON      ServerStatus = "ON"
	UNKNOWN ServerStatus = "UNKNOWN"
)

// CreateServerRequest defines model for CreateServerRequest.
type CreateServerRequest struct {
	Ipv4       string `json:"ipv4"`
	ServerId   string `json:"server_id"`
	ServerName string `json:"server_name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Code      *string `json:"code,omitempty"`
	Message   *string `json:"message,omitempty"`
	RequestId *string `json:"request_id,omitempty"`
}

// GetListServersResponse defines model for GetListServersResponse.
type GetListServersResponse struct {
	Items *[]Server `json:"items,omitempty"`
	Total *int      `json:"total,omitempty"`
}

// ImportServerResponse defines model for ImportServerResponse.
type ImportServerResponse struct {
	IdFailed     []string `json:"id_failed"`
	IdSuccess    []string `json:"id_success"`
	TotalFailed  int      `json:"total_failed"`
	TotalSuccess int      `json:"total_success"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	AccessToken  *string `json:"access_token,omitempty"`
	RefreshToken *string `json:"refresh_token,omitempty"`
}

// LogoutRequest defines model for LogoutRequest.
type LogoutRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// ReportServerRequest defines model for ReportServerRequest.
type ReportServerRequest struct {
	From      time.Time             `json:"from"`
	Receivers []openapi_types.Email `json:"receivers"`
	To        time.Time             `json:"to"`
}

// Server defines model for Server.
type Server struct {
	CreatedAt         *time.Time   `json:"created_at,omitempty"`
	Ipv4              string       `json:"ipv4"`
	LastPingAt        *time.Time   `json:"last_ping_at,omitempty"`
	MetadataUpdatedAt *time.Time   `json:"metadata_updated_at,omitempty"`
	ServerId          string       `json:"server_id"`
	ServerName        string       `json:"server_name"`
	Status            ServerStatus `json:"status"`
}

// ServerStatus defines model for Server.Status.
type ServerStatus string

// UpdateServerRequest defines model for UpdateServerRequest.
type UpdateServerRequest struct {
	Ipv4       *string `json:"ipv4,omitempty"`
	ServerName *string `json:"server_name,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Conflict defines model for Conflict.
type Conflict = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// InternalError defines model for InternalError.
type InternalError = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetListServersParams defines parameters for GetListServers.
type GetListServersParams struct {
	From      int    `form:"from" json:"from"`
	To        int    `form:"to" json:"to"`
	SortField string `form:"sort_field" json:"sort_field"`
	Desc      bool   `form:"desc" json:"desc"`
}

// ExportServersParams defines parameters for ExportServers.
type ExportServersParams struct {
	From      int    `form:"from" json:"from"`
	To        int    `form:"to" json:"to"`
	SortField string `form:"sort_field" json:"sort_field"`
	Desc      bool   `form:"desc" json:"desc"`
}

// ImportServerMultipartBody defines parameters for ImportServer.
type ImportServerMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = LogoutRequest

// RefreshTokenJSONRequestBody defines body for RefreshToken for application/json ContentType.
type RefreshTokenJSONRequestBody = RefreshTokenRequest

// CreateServerJSONRequestBody defines body for CreateServer for application/json ContentType.
type CreateServerJSONRequestBody = CreateServerRequest

// ImportServerMultipartRequestBody defines body for ImportServer for multipart/form-data ContentType.
type ImportServerMultipartRequestBody ImportServerMultipartBody

// GenerateServerReportJSONRequestBody defines body for GenerateServerReport for application/json ContentType.
type GenerateServerReportJSONRequestBody = ReportServerRequest

// UpdateServerJSONRequestBody defines body for UpdateServer for application/json ContentType.
type UpdateServerJSONRequestBody = UpdateServerRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login
	// (POST /auth/login)
	Login(c *gin.Context)
	// Logout
	// (POST /auth/logout)
	Logout(c *gin.Context)
	// Refresh token
	// (POST /auth/refresh)
	RefreshToken(c *gin.Context)
	// Download report file
	// (GET /report/{filename})
	GetReportFile(c *gin.Context, filename string)
	// Get list servers
	// (GET /servers)
	GetListServers(c *gin.Context, params GetListServersParams)
	// Create server
	// (POST /servers)
	CreateServer(c *gin.Context)
	// Export servers
	// (GET /servers/export)
	ExportServers(c *gin.Context, params ExportServersParams)
	// Import server
	// (POST /servers/import)
	ImportServer(c *gin.Context)
	// Generate server report
	// (POST /servers/report)
	GenerateServerReport(c *gin.Context)
	// Delete server
	// (DELETE /servers/{server_id})
	DeleteServer(c *gin.Context, serverId string)
	// Update server
	// (PATCH /servers/{server_id})
	UpdateServer(c *gin.Context, serverId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Login(c)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.Logout(c)
}

// RefreshToken operation middleware
func (siw *ServerInterfaceWrapper) RefreshToken(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RefreshToken(c)
}

// GetReportFile operation middleware
func (siw *ServerInterfaceWrapper) GetReportFile(c *gin.Context) {

	var err error

	// ------------- Path parameter "filename" -------------
	var filename string

	err = runtime.BindStyledParameter("simple", false, "filename", c.Param("filename"), &filename)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter filename: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(ApiKeyAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetReportFile(c, filename)
}

// GetListServers operation middleware
func (siw *ServerInterfaceWrapper) GetListServers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"server:read"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetListServersParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", c.Request.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "sort_field" -------------

	if paramValue := c.Query("sort_field"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument sort_field is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "sort_field", c.Request.URL.Query(), &params.SortField)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_field: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "desc" -------------

	if paramValue := c.Query("desc"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument desc is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "desc", c.Request.URL.Query(), &params.Desc)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter desc: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetListServers(c, params)
}

// CreateServer operation middleware
func (siw *ServerInterfaceWrapper) CreateServer(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"server:create"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateServer(c)
}

// ExportServers operation middleware
func (siw *ServerInterfaceWrapper) ExportServers(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{"server:export"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportServersParams

	// ------------- Required query parameter "from" -------------

	if paramValue := c.Query("from"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument from is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", c.Request.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter from: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := c.Query("to"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument to is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", c.Request.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter to: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "sort_field" -------------

	if paramValue := c.Query("sort_field"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument sort_field is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "sort_field", c.Request.URL.Query(), &params.SortField)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter sort_field: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Required query parameter "desc" -------------

	if paramValue := c.Query("desc"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument desc is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "desc", c.Request.URL.Query(), &params.Desc)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter desc: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ExportServers(c, params)
}

// ImportServer operation middleware
func (siw *ServerInterfaceWrapper) ImportServer(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"server:import"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ImportServer(c)
}

// GenerateServerReport operation middleware
func (siw *ServerInterfaceWrapper) GenerateServerReport(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{"server:report"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GenerateServerReport(c)
}

// DeleteServer operation middleware
func (siw *ServerInterfaceWrapper) DeleteServer(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId string

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"server:delete"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteServer(c, serverId)
}

// UpdateServer operation middleware
func (siw *ServerInterfaceWrapper) UpdateServer(c *gin.Context) {

	var err error

	// ------------- Path parameter "server_id" -------------
	var serverId string

	err = runtime.BindStyledParameter("simple", false, "server_id", c.Param("server_id"), &serverId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter server_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{"server:update"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateServer(c, serverId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth/login", wrapper.Login)
	router.POST(options.BaseURL+"/auth/logout", wrapper.Logout)
	router.POST(options.BaseURL+"/auth/refresh", wrapper.RefreshToken)
	router.GET(options.BaseURL+"/report/:filename", wrapper.GetReportFile)
	router.GET(options.BaseURL+"/servers", wrapper.GetListServers)
	router.POST(options.BaseURL+"/servers", wrapper.CreateServer)
	router.GET(options.BaseURL+"/servers/export", wrapper.ExportServers)
	router.POST(options.BaseURL+"/servers/import", wrapper.ImportServer)
	router.POST(options.BaseURL+"/servers/report", wrapper.GenerateServerReport)
	router.DELETE(options.BaseURL+"/servers/:server_id", wrapper.DeleteServer)
	router.PATCH(options.BaseURL+"/servers/:server_id", wrapper.UpdateServer)
}

type BadRequestJSONResponse ErrorResponse

type ConflictJSONResponse ErrorResponse

type ForbiddenJSONResponse ErrorResponse

type InternalErrorJSONResponse ErrorResponse

type NotFoundJSONResponse ErrorResponse

type UnauthorizedJSONResponse ErrorResponse

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse LoginResponse

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Login500JSONResponse struct{ InternalErrorJSONResponse }

func (response Login500JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type LogoutRequestObject struct {
	Body *LogoutJSONRequestBody
}

type LogoutResponseObject interface {
	VisitLogoutResponse(w http.ResponseWriter) error
}

type Logout200Response struct {
}

func (response Logout200Response) VisitLogoutResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type Logout401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Logout401JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type Logout500JSONResponse struct{ InternalErrorJSONResponse }

func (response Logout500JSONResponse) VisitLogoutResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type RefreshTokenRequestObject struct {
	Body *RefreshTokenJSONRequestBody
}

type RefreshTokenResponseObject interface {
	VisitRefreshTokenResponse(w http.ResponseWriter) error
}

type RefreshToken200JSONResponse LoginResponse

func (response RefreshToken200JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshToken401JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type RefreshToken500JSONResponse struct{ InternalErrorJSONResponse }

func (response RefreshToken500JSONResponse) VisitRefreshTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetReportFileRequestObject struct {
	Filename string `json:"filename"`
}

type GetReportFileResponseObject interface {
	VisitGetReportFileResponse(w http.ResponseWriter) error
}

type GetReportFile200ApplicationoctetStreamResponse struct {
	Body          io.Reader
	ContentLength int64
}

func (response GetReportFile200ApplicationoctetStreamResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/octet-stream")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetReportFile401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetReportFile401JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetReportFile403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetReportFile403JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetReportFile404JSONResponse struct{ NotFoundJSONResponse }

func (response GetReportFile404JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type GetReportFile500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetReportFile500JSONResponse) VisitGetReportFileResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GetListServersRequestObject struct {
	Params GetListServersParams
}

type GetListServersResponseObject interface {
	VisitGetListServersResponse(w http.ResponseWriter) error
}

type GetListServers200JSONResponse GetListServersResponse

func (response GetListServers200JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers400JSONResponse struct{ BadRequestJSONResponse }

func (response GetListServers400JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetListServers401JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers403JSONResponse struct{ ForbiddenJSONResponse }

func (response GetListServers403JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GetListServers500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetListServers500JSONResponse) VisitGetListServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type CreateServerRequestObject struct {
	Body *CreateServerJSONRequestBody
}

type CreateServerResponseObject interface {
	VisitCreateServerResponse(w http.ResponseWriter) error
}

type CreateServer201JSONResponse Server

func (response CreateServer201JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateServer400JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateServer401JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response CreateServer403JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer409JSONResponse struct{ ConflictJSONResponse }

func (response CreateServer409JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)

	return json.NewEncoder(w).Encode(response)
}

type CreateServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateServer500JSONResponse) VisitCreateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ExportServersRequestObject struct {
	Params ExportServersParams
}

type ExportServersResponseObject interface {
	VisitExportServersResponse(w http.ResponseWriter) error
}

type ExportServers200ResponseHeaders struct {
	ContentDisposition string
}

type ExportServers200ApplicationvndOpenxmlformatsOfficedocumentSpreadsheetmlSheetResponse struct {
	Body          io.Reader
	Headers       ExportServers200ResponseHeaders
	ContentLength int64
}

func (response ExportServers200ApplicationvndOpenxmlformatsOfficedocumentSpreadsheetmlSheetResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	w.Header().Set("Content-Disposition", fmt.Sprint(response.Headers.ContentDisposition))
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportServers400JSONResponse struct{ BadRequestJSONResponse }

func (response ExportServers400JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ExportServers401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ExportServers401JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ExportServers403JSONResponse struct{ ForbiddenJSONResponse }

func (response ExportServers403JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ExportServers500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportServers500JSONResponse) VisitExportServersResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type ImportServerRequestObject struct {
	Body *multipart.Reader
}

type ImportServerResponseObject interface {
	VisitImportServerResponse(w http.ResponseWriter) error
}

type ImportServer200JSONResponse ImportServerResponse

func (response ImportServer200JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer400JSONResponse struct{ BadRequestJSONResponse }

func (response ImportServer400JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ImportServer401JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response ImportServer403JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type ImportServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response ImportServer500JSONResponse) VisitImportServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReportRequestObject struct {
	Body *GenerateServerReportJSONRequestBody
}

type GenerateServerReportResponseObject interface {
	VisitGenerateServerReportResponse(w http.ResponseWriter) error
}

type GenerateServerReport202Response struct {
}

func (response GenerateServerReport202Response) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.WriteHeader(202)
	return nil
}

type GenerateServerReport400JSONResponse struct{ BadRequestJSONResponse }

func (response GenerateServerReport400JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GenerateServerReport401JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport403JSONResponse struct{ ForbiddenJSONResponse }

func (response GenerateServerReport403JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type GenerateServerReport500JSONResponse struct{ InternalErrorJSONResponse }

func (response GenerateServerReport500JSONResponse) VisitGenerateServerReportResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServerRequestObject struct {
	ServerId string `json:"server_id"`
}

type DeleteServerResponseObject interface {
	VisitDeleteServerResponse(w http.ResponseWriter) error
}

type DeleteServer204Response struct {
}

func (response DeleteServer204Response) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteServer401JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response DeleteServer403JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServer404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteServer404JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type DeleteServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteServer500JSONResponse) VisitDeleteServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServerRequestObject struct {
	ServerId string `json:"server_id"`
	Body     *UpdateServerJSONRequestBody
}

type UpdateServerResponseObject interface {
	VisitUpdateServerResponse(w http.ResponseWriter) error
}

type UpdateServer200JSONResponse Server

func (response UpdateServer200JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateServer400JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateServer401JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer403JSONResponse struct{ ForbiddenJSONResponse }

func (response UpdateServer403JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateServer404JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)

	return json.NewEncoder(w).Encode(response)
}

type UpdateServer500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateServer500JSONResponse) VisitUpdateServerResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login
	// (POST /auth/login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Logout
	// (POST /auth/logout)
	Logout(ctx context.Context, request LogoutRequestObject) (LogoutResponseObject, error)
	// Refresh token
	// (POST /auth/refresh)
	RefreshToken(ctx context.Context, request RefreshTokenRequestObject) (RefreshTokenResponseObject, error)
	// Download report file
	// (GET /report/{filename})
	GetReportFile(ctx context.Context, request GetReportFileRequestObject) (GetReportFileResponseObject, error)
	// Get list servers
	// (GET /servers)
	GetListServers(ctx context.Context, request GetListServersRequestObject) (GetListServersResponseObject, error)
	// Create server
	// (POST /servers)
	CreateServer(ctx context.Context, request CreateServerRequestObject) (CreateServerResponseObject, error)
	// Export servers
	// (GET /servers/export)
	ExportServers(ctx context.Context, request ExportServersRequestObject) (ExportServersResponseObject, error)
	// Import server
	// (POST /servers/import)
	ImportServer(ctx context.Context, request ImportServerRequestObject) (ImportServerResponseObject, error)
	// Generate server report
	// (POST /servers/report)
	GenerateServerReport(ctx context.Context, request GenerateServerReportRequestObject) (GenerateServerReportResponseObject, error)
	// Delete server
	// (DELETE /servers/{server_id})
	DeleteServer(ctx context.Context, request DeleteServerRequestObject) (DeleteServerResponseObject, error)
	// Update server
	// (PATCH /servers/{server_id})
	UpdateServer(ctx context.Context, request UpdateServerRequestObject) (UpdateServerResponseObject, error)
}

type StrictHandlerFunc = strictgin.StrictGinHandlerFunc
type StrictMiddlewareFunc = strictgin.StrictGinMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// Login operation middleware
func (sh *strictHandler) Login(ctx *gin.Context) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Logout operation middleware
func (sh *strictHandler) Logout(ctx *gin.Context) {
	var request LogoutRequestObject

	var body LogoutJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.Logout(ctx, request.(LogoutRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Logout")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(LogoutResponseObject); ok {
		if err := validResponse.VisitLogoutResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// RefreshToken operation middleware
func (sh *strictHandler) RefreshToken(ctx *gin.Context) {
	var request RefreshTokenRequestObject

	var body RefreshTokenJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshToken(ctx, request.(RefreshTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(RefreshTokenResponseObject); ok {
		if err := validResponse.VisitRefreshTokenResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetReportFile operation middleware
func (sh *strictHandler) GetReportFile(ctx *gin.Context, filename string) {
	var request GetReportFileRequestObject

	request.Filename = filename

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetReportFile(ctx, request.(GetReportFileRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetReportFile")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetReportFileResponseObject); ok {
		if err := validResponse.VisitGetReportFileResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetListServers operation middleware
func (sh *strictHandler) GetListServers(ctx *gin.Context, params GetListServersParams) {
	var request GetListServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetListServers(ctx, request.(GetListServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetListServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GetListServersResponseObject); ok {
		if err := validResponse.VisitGetListServersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateServer operation middleware
func (sh *strictHandler) CreateServer(ctx *gin.Context) {
	var request CreateServerRequestObject

	var body CreateServerJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateServer(ctx, request.(CreateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(CreateServerResponseObject); ok {
		if err := validResponse.VisitCreateServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportServers operation middleware
func (sh *strictHandler) ExportServers(ctx *gin.Context, params ExportServersParams) {
	var request ExportServersRequestObject

	request.Params = params

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ExportServers(ctx, request.(ExportServersRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportServers")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ExportServersResponseObject); ok {
		if err := validResponse.VisitExportServersResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// ImportServer operation middleware
func (sh *strictHandler) ImportServer(ctx *gin.Context) {
	var request ImportServerRequestObject

	if reader, err := ctx.Request.MultipartReader(); err == nil {
		request.Body = reader
	} else {
		ctx.Error(err)
		return
	}

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ImportServer(ctx, request.(ImportServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ImportServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(ImportServerResponseObject); ok {
		if err := validResponse.VisitImportServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// GenerateServerReport operation middleware
func (sh *strictHandler) GenerateServerReport(ctx *gin.Context) {
	var request GenerateServerReportRequestObject

	var body GenerateServerReportJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GenerateServerReport(ctx, request.(GenerateServerReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GenerateServerReport")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(GenerateServerReportResponseObject); ok {
		if err := validResponse.VisitGenerateServerReportResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteServer operation middleware
func (sh *strictHandler) DeleteServer(ctx *gin.Context, serverId string) {
	var request DeleteServerRequestObject

	request.ServerId = serverId

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteServer(ctx, request.(DeleteServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(DeleteServerResponseObject); ok {
		if err := validResponse.VisitDeleteServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateServer operation middleware
func (sh *strictHandler) UpdateServer(ctx *gin.Context, serverId string) {
	var request UpdateServerRequestObject

	request.ServerId = serverId

	var body UpdateServerJSONRequestBody
	if err := ctx.ShouldBind(&body); err != nil {
		ctx.Status(http.StatusBadRequest)
		ctx.Error(err)
		return
	}
	request.Body = &body

	handler := func(ctx *gin.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateServer(ctx, request.(UpdateServerRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateServer")
	}

	response, err := handler(ctx, request)

	if err != nil {
		ctx.Error(err)
		ctx.Status(http.StatusInternalServerError)
	} else if validResponse, ok := response.(UpdateServerResponseObject); ok {
		if err := validResponse.VisitUpdateServerResponse(ctx.Writer); err != nil {
			ctx.Error(err)
		}
	} else if response != nil {
		ctx.Error(fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwLvPiq20+aAng/3IX1JkG03LdIWXSANDEYa2exKpEqO2ngD/fcFX2RT",
	"MuXYTeJk0X6KJZEzw3meeSGZa5KIohQcOCoyviYSVCm4AvPwnKZn8LUChfopERyBm5+0LHOWUGSCD78o",
	"wfU7lcygoPrXvyVkZEz+NVyKHtqvavhKSiHPnBJS13VMUlCJZKUWRsZaZySd0jomLwTPcpbs0IAzUKKS",
	"CURJo7qOyZGQlyxNge/OjqXKOiYnHEFymptZu7OhURspkN9ARmDU1zE5FXgkKp4+ACxcYJQZ3XVMPnJa",
	"4UxI9hfs0JaWVv3ZzdSCX0igCO+Nv7zgKaUoQSKzgcXKbwf6byZkQZGM7YuY4LwEMiYKJeNTvT7r9wkz",
	"i+v7ymkBge91THQgMaldc+6Jak+MrfKLhXZx+QUs69uOWFlFIlII2lWAUnQa/uZiO7ykOmDEMeAbptB6",
	"VPVbwxCK9o91GFtxZKmQSknn5lkgzT3bGEeY6qEh406KUkhs0O41LZ1klOWWogvzVlzTtYSlE1UlCSi1",
	"3TyzAk9jdyHNCE94YK0+d9rjW5Z11MXeYkOUeiOmjPfGRUmV+i5k2oqNxctAfFRK56dN6L8YGS8FrjGw",
	"D0pqVj1B8aetBQF+ZxLUrHdEHdYpKuz1ygYi/ZW2h4fWeGZHfNADdqnVj5UerZkURQv9lCLsITPABZyd",
	"ANNpoRUgi7lQUJaH5q1GzKY6O6s25pr5vjGh1buEs5pETb1IJxQ3X/bG5SOnCicl49OtxBeANKVIJ1WZ",
	"bm3bbSpWTBRSrIxfgFeF9vDbUxKTt0dHJCYfT1+fvv106rn3x0rdQk0Ip49mzXdcv/tTVEe/mZJUkuH8",
	"va5ULumU7DXMDyucGeW6BZkBTUGSmFjR5I+9w3cne69hvrTCztJWXAKVIJv59umoMf23Tx+I62D0LPt1",
	"KWWGWNoeiPHMhEm7Fzp8dxJlQkYF5XTK+NS1iqYwMMy1COvM6Hc9AgrgGB2+OyEx0cOskP3BaDDSlooS",
	"OC0ZGZOng9HgqUnWODNOGOqea5jr9GwAERYYDYtp8k5SMrbZmyy6jOcind9ZW9gqXXWbcygrMC+83dOT",
	"0eiudfe3pGZA5IpyVuXamQej/T65C0OH7V42Jv+xVq+f1N6OGNZWRUHl3IMA6VTpYNTiyYUes0BQVLgW",
	"Qv393jD0Ku3mIK44W1T4kN52OYKMz69b0X1+UV90wLDO7EPDle1+OPxe4Z5ACbUjjy2+jHGR85bF7mHC",
	"yzkrQgdIAFhpGq3hdcZy0OWh1hqnEAD3GNB2ZUcst52xpAWgaajOXaXRCXhZZxqZpItO7Hm6W+YutkJO",
	"JAi4p1ACLdoILsrtJePaG6t9wApuL8V3ngtzpqTXGWn7vcDN5z+M5MHo6c2TWoc4B6ODm2csTlbuKDv4",
	"vUM3O4Sc41HKkMJSqinqa4jkbdJ7mPS1AgNaQyXbO/fTKIWMVjmS8SgObFDDQl0nfqPI/S1kKiFxkjHI",
	"061Y3yNN83MTOZdC5ED51uGzXeLrOV0JRNIxYJQzhU2DF4iiDdjqHSnvLvDuvMq6vn4sgaakE1RdP3kB",
	"5faAF3XcU2z9w8N7Krah88mNiu3+nZnQnL2tcsztFNye+HGT6mD035tnvPDuEO6NhdZdXR5aoB0LQyT0",
	"8voQrnQB6E3vr66WRze/svtDZvdvPB3oTfJVkdtuSO2JLGMJpCKp9N56oEqdldQMAIt8YP7euouy+Icz",
	"f+zOIuzth7V67yVTpVDMTu9unygiTWba2P9FTT/5/8+OzWpwlaurz4Ssc379c5YbF6WdQG+Dc1Oks6KJ",
	"9HAJ8m801pagosqRlVTiUBNqL6VI7bldIlKNkmaabiCXsz4051K3pfPyyi1wgOx03szyzkmuaXZXD+R2",
	"ug0NXieF7mXNuIgmCZSPvlDeWzg4KnfCwflms7pnNz790XAMXD8u+iUz+r5OQVavRzai35PVDGtlRVNr",
	"PRM8+lpBBemvnl337CHWNEA3/+kgG6jX0ud6cdNQWxByQFhl0UvzfpFTbz5l8S8wbnPMcrBKDWtL+lOd",
	"gQR54MDqHomYt2uyh7mRSGarIPsXR/cN8t1nn9C1146LX/+20Br3T8pej4fm9g63S3Pr0XVFcoNbhuZM",
	"8PyaVDJ3d4Xj4TAXCc1nQuH42ejZiOixTv51w/0G64v67wAAAP//HUr55YEoAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
