openapi: 3.0.3

info:
  title: Server Management API
  version: 1.0.0
  description: API for managing servers

servers:
  - url: http://localhost:8080

tags:
  - name: Server

security:
  - bearerAuth: []

paths:
  /servers:
    get:
      tags:
        - Server
      summary: Get list servers
      operationId: GetListServers

      security:
        - bearerAuth:
            - server:read

      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: integer
            default: 0

        - name: to
          in: query
          required: true
          schema:
            type: integer
            default: 10

        - name: sort_field
          in: query
          required: true
          schema:
            type: string

        - name: desc
          in: query
          required: true
          schema:
            type: boolean

      responses:
        "200":
          description: Get list servers successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetListServersResponse"

        "400":
          $ref: "#/components/responses/BadRequest"

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "500":
          $ref: "#/components/responses/InternalError"

    post:
      tags:
        - Server
      summary: Create server
      operationId: CreateServer

      security:
        - bearerAuth:
            - server:create

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateServerRequest"

      responses:
        "201":
          description: Server created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Server"

        "400":
          $ref: "#/components/responses/BadRequest"

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "409":
          $ref: "#/components/responses/Conflict"

        "500":
          $ref: "#/components/responses/InternalError"

  /servers/{server_id}:
    patch:
      tags:
        - Server
      summary: Update server
      operationId: UpdateServer

      security:
        - bearerAuth:
            - server:update

      parameters:
        - name: server_id
          in: path
          required: true
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateServerRequest"

      responses:
        "200":
          description: Updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Server"
        
        "400":
          $ref: "#/components/responses/BadRequest"

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "404":
          $ref: "#/components/responses/NotFound"

        "500":
          $ref: "#/components/responses/InternalError"

    delete:
      tags:
        - Server
      summary: Delete server
      operationId: DeleteServer

      security:
        - bearerAuth:
            - server:delete

      parameters:
        - name: server_id
          in: path
          required: true
          schema:
            type: string

      responses:
        "204":
          description: Deleted successfully

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "404":
          $ref: "#/components/responses/NotFound"

        "500":
          $ref: "#/components/responses/InternalError"
  
  /servers/import:
    post:
      tags:
        - Server
      summary: Import server
      operationId: ImportServer

      security:
        - bearerAuth:
            - server:import

      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object

              required:
                - file

              properties:
                file:
                  type: string
                  format: binary

      responses:
        "200":
          description: Import accepted
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ImportServerResponse"

        "400":
          $ref: "#/components/responses/BadRequest"

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "500":
          $ref: "#/components/responses/InternalError"

  /servers/export:
    get:
      tags:
        - Server
      summary: Export servers
      operationId: ExportServers

      security:
        - bearerAuth:
            - server:export

      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: integer
            default: 0

        - name: to
          in: query
          required: true
          schema:
            type: integer
            default: 10

        - name: sort_field
          in: query
          required: true
          schema:
            type: string

        - name: desc
          in: query
          required: true
          schema:
            type: boolean

      responses:
        "200":
          description: Export servers successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

        "400":
          $ref: "#/components/responses/BadRequest"

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "500":
          $ref: "#/components/responses/InternalError"

  /servers/report:
    post:
      tags:
        - Server
      summary: Generate server report
      operationId: GenerateServerReport

      security:
        - bearerAuth:
            - server:report

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ReportServerRequest"


      responses:
        "202":
          description: Report generation queued successfully

        "400":
          $ref: "#/components/responses/BadRequest"

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "500":
          $ref: "#/components/responses/InternalError"

  /report/{filename}:
    get:
      tags:
        - File
      summary: Download report file
      operationId: GetReportFile

      security:
        - bearerAuth:
            - report:download

      parameters:
        - name: filename
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: Download report file successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

        "401":
          $ref: "#/components/responses/Unauthorized"

        "403":
          $ref: "#/components/responses/Forbidden"

        "404":
          $ref: "#/components/responses/NotFound"

        "500":
          $ref: "#/components/responses/InternalError"

  /auth/login:
    post:
      summary: Login
      operationId: Login
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /auth/refresh:
    post:
      summary: Refresh token
      operationId: RefreshToken
      tags:
        - auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refreshed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Server:
      type: object
      required:
        - server_id
        - server_name
        - ipv4
        - status
      properties:
        server_id:
          type: string

        server_name:
          type: string

        ipv4:
          type: string
          format: ipv4

        status:
          type: string
          enum:
            - ON
            - OFF
            - UNKNOWN

        created_at:
          type: string
          format: date-time

        metadata_updated_at:
          type: string
          format: date-time

        last_ping_at:
          type: string
          format: date-time

    CreateServerRequest:
      type: object
      required:
        - server_id
        - server_name
        - ipv4

      properties:
        server_id:
          type: string

        server_name:
          type: string

        ipv4:
          type: string
          format: ipv4

    UpdateServerRequest:
      type: object
      properties:
        server_name:
          type: string

        ipv4:
          type: string
          format: ipv4

    GetListServersResponse:
      type: object
      properties:
        total:
          type: integer

        items:
          type: array
          items:
            $ref: "#/components/schemas/Server"
    
    ImportServerResponse:
      type: object
      required:
        - total_success
        - id_success
        - total_failed
        - id_failed
      properties:
        total_success:
          type: integer

        id_success:
          type: array
          items:
            type: string

        total_failed:
          type: integer

        id_failed:
          type: array
          items:
            type: string
    
    ReportServerRequest:
      type: object
      required:
        - from
        - to
        - receivers

      properties:
        from:
          type: string
          format: date-time

        to:
          type: string
          format: date-time

        receivers:
          type: array
          items:
            type: string
            format: email
    
    LoginRequest:
      type: object
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
          format: password

    RefreshTokenRequest:
      type: object
      required:
        - refresh_token
      properties:
        refresh_token:
          type: string

    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
        refresh_token:
          type: string
        expires_in:
          type: integer
          description: Access token expiry in seconds

    ErrorResponse:
      type: object
      properties:
        code:
          type: string

        message:
          type: string

        request_id:
          type: string

  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    
    Forbidden:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Conflict:
      description: Resource conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
            
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT